### ISSUE TITLE
Bug in DateTimeUtils.java on Adroid API < 24

### ISSUE THREAD

**Issue by Nicole1338** [Freeyourgadget/Gadgetbridge#1055]
#### Your issue is:
I compiled the current Version from the master and couldn't connect to my Amazfit Bip.
After debugging I found the solution.
In:
 nodomain/freeyourgadget/gadgetbridge/util/DateTimeUtils.java

there is line 36 a call to new SimpleDateForma()
-> public static SimpleDateFormat ISO_8601_FORMAT = new SimpleDateFormat("yyyy-MM-dd'T'hh:mm:ssXXX", Locale.US);

There is a bug on Android System running API level < 24 with the pattern "XXX".
See also: https://stackoverflow.com/questions/44588429/unknown-pattern-character-x-when-using-simpledateformat/44588864

So I changed the pattern to
 -> new SimpleDateFormat("yyyy-MM-dd'T'hh:mm:ssZZZ", Locale.US);

Now I can connect to my watch, but I still have a lack with the timezone. I'm in Germany and currently we have summer time, so it is UTC+2, but the activity overview just shows UTC+1

#### Your wearable device is:
Amazfit Bip 
FW: 0.1.1.14
HW: V0.11.2.4

#### Your android version is:
Android 6.0.1 on Google Nexus 5

#### Your Gadgetbridge version is:
Current Version from Master

Best,
Nicole

**Comment by danielegobbetti** [comment]
Thanks for the precise information and the research. What's unclear to me is:
when you write that you couldn't connect to the watch, were you getting an exception?
I ask because it seems strange to me that this bug went under our radar for so long (I personally test on an API19 device, albeit not with the bip)

**Comment by Nicole1338** [comment]
Yes, there was exception. See attached the logcat output. The mentioned line was added with the merge of the bip-wip branch into the master, so it's kind of new.

`E/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Queue Dispatch Thread died: nulljava.lang.ExceptionInInitializerError: null
                                                                                                                                   	at nodomain.freeyourgadget.gadgetbridge.util.DateTimeUtils.formatDateTime(DateTimeUtils.java) ~[na:na]
                                                                                                                                   	at nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEAction.getCreationTime(BtLEAction.java:70) ~[na:0.0]
                                                                                                                                   	at nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEAction.toString(BtLEAction.java:76) ~[na:0.0]
                                                                                                                                   	at java.lang.StringBuilder.append(StringBuilder.java:202) ~[na:0.0]
                                                                                                                                   	at nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue$1.run(BtLEQueue.java:105) ~[na:0.0]
                                                                                                                                   Caused by: java.lang.IllegalArgumentException: Unknown pattern character 'X'
                                                                                                                                   	at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323) ~[na:0.0]
                                                                                                                                   	at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:312) ~[na:0.0]
                                                                                                                                   	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365) ~[na:0.0]
                                                                                                                                   	at nodomain.freeyourgadget.gadgetbridge.util.DateTimeUtils.<clinit>(DateTimeUtils.java:36) ~[na:na]
                                                                                                                                   	... 5 common frames omitted`

**Comment by danielegobbetti** [comment]
I see, thanks!

**Comment by danielegobbetti** [comment]
We are getting reports of this error on other channels, hence I am reopening this issue
