### ISSUE TITLE
App crashes on connection to Pebble after upgrading to 0.26.0

### ISSUE THREAD

**Issue by exmosis** [Freeyourgadget/Gadgetbridge#1074]
Hi all, 

I upgraded to 0.26.0 this morning, via F-Droid, but GadgetBridge now crashes when it tries to connect to my Pebble watch. I'm not sure if it's a result of the upgrade process itself, or the new version.

SmartWatch: Pebble Time, Firmware v4.3, Hardware snowy23
Android: 6.0.1 on Fairphone 2
GadgetBridge: 0.2.6.0

Here are the logs from my phone showing the startup and subsequent crash:

17:35:11.428 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.26.0
17:35:20.096 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
17:35:20.128 [main] INFO  n.f.g.s.d.p.PebbleProtocol - setting always ACK PebbleKit to false
17:35:20.128 [main] INFO  n.f.g.s.d.p.PebbleProtocol - setting enable PebbleKit support to true
17:35:20.146 [Thread-2314] INFO  n.f.g.s.d.p.PebbleIoThread - found service UUID 00001101-0000-1000-8000-00805f9b34fb
17:35:20.147 [Thread-2314] INFO  n.f.g.s.d.p.PebbleIoThread - found service UUID 00000000-0000-1000-8000-00805f9b34fb
17:35:20.147 [Thread-2314] INFO  n.f.g.s.d.p.PebbleIoThread - found service UUID 00000000-0000-1000-8000-00805f9b34fb
17:35:20.147 [Thread-2314] INFO  n.f.g.s.d.p.PebbleIoThread - found service UUID ffcacade-afde-cade-defa-cade00000000
17:35:20.392 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
17:35:20.448 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Got metadata changed intent, but nothing changed, ignoring.
17:35:20.449 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Update Music State: state=1, position= 0
17:35:20.450 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Got metadata changed intent, but nothing changed, ignoring.
17:35:20.450 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Got state changed intent, but not enough has changed, ignoring.
17:35:20.451 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
17:35:20.829 [main] INFO  n.f.g.e.BluetoothConnectReceiver - connection attempt detected from or to B0:B4:48:89:D1:9F(Pebble Time D19F)
17:35:21.096 [Thread-2314] INFO  n.f.g.s.d.p.PebbleProtocol - setting force protocol to false
17:35:21.211 [Thread-2314] INFO  n.f.g.s.d.p.PebbleProtocol - Pebble asked for Phone/App Version - repLYING!
17:35:21.413 [Thread-2314] INFO  n.f.g.s.d.p.PebbleProtocol - Pebble firmware major detected as 4
17:35:21.413 [Thread-2314] INFO  n.f.g.s.d.p.PebbleIoThread - syncing time
17:35:21.413 [Thread-2314] INFO  n.f.g.s.d.p.PebbleProtocol - Europe/London
17:35:21.746 [Thread-2314] INFO  n.f.g.s.AbstractDeviceSupport - Got event for VERSION_INFO
17:35:21.760 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
17:35:21.789 [main] ERROR n.f.g.LoggingExceptionHandler - Uncaught exception: null
java.lang.ExceptionInInitializerError: null
        at nodomain.freeyourgadget.gadgetbridge.database.DBHelper.isValidNow(DBHelper.java:315) ~[na:0.0]
        at nodomain.freeyourgadget.gadgetbridge.database.DBHelper.hasUpToDateDeviceAttributes(DBHelper.java:494) ~[na:0.0]
        at nodomain.freeyourgadget.gadgetbridge.database.DBHelper.ensureDeviceAttributes(DBHelper.java:462) ~[na:0.0]
        at nodomain.freeyourgadget.gadgetbridge.database.DBHelper.getDevice(DBHelper.java:400) ~[na:0.0]
        at nodomain.freeyourgadget.gadgetbridge.devices.DeviceManager$1.onReceive(DeviceManager.java:97) ~[na:0.0]
        at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:311) ~[na:0.0]
        at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:47) ~[na:0.0]
        at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:120) ~[na:0.0]
        at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
        at android.os.Looper.loop(Looper.java:148) ~[na:0.0]
        at android.app.ActivityThread.main(ActivityThread.java:5417) ~[na:0.0]
        at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) ~[na:0.0]
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) ~[na:0.0]
Caused by: java.lang.IllegalArgumentException: Unknown pattern character 'X'
        at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323) ~[na:0.0]
        at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:312) ~[na:0.0]
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365) ~[na:0.0]
        at nodomain.freeyourgadget.gadgetbridge.util.DateTimeUtils.<clinit>(DateTimeUtils.java:36) ~[na:na]
        ... 14 common frames omitted

Any ideas? F-Droid won't let me downgrade to 0.25.1 for some reason, so can't test under an older version.

If I uninstall GadgetBridge on my phone (again, via F-Droid) and reinstall it, will any of my previous data and configuration be lost?

Many thanks!

**Comment by danielegobbetti** [comment]
Unfortunately a bug sneaked in release 0.26.0 the issue is already fixed in master and a release will follow shortly. There are options to export the database and settings (and to import them) that do not require being connected to a device. You should be able to export-uninstall-install_old_version-import without losing anything but please check the exported file contents before uninstalling the app.

Or just wait (hopefully only a few hours/a day) until the update is available on f-droid.

**Comment by exmosis** [comment]
That's great news, thanks Daniele - Happy to wait a while, if I know a fix is on the way.

**Comment by danielegobbetti** [comment]
Version 0.26.1 is available on f-droid, and should fix the issue.
