### ISSUE TITLE
Activity do not load on Amazfit Bip (invalid package counter)

### ISSUE THREAD

**Issue by dazzzl** [Freeyourgadget/Gadgetbridge#1144]
#### Before opening an issue please confirm the following:
- [x ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

One of my activities do not load because of the following error: 

Error fetching sport details, invalid package counter: 76, last was: 74

If I try this more often, the counter has different values, but also not match.

*In case of a bug, do not forget to attach logs!*

01:12:37.349 [Binder:3764_10] WARN  n.f.g.s.d.h.m.o.FetchSportsDetailsOperation - sports details: 0x49 0x06 0x6e 0xc3 0x01 0xd8 0xff 0x00 0x00
 0x01 0x6f 0xae 0x00 0x00 0x00 0x00 0x00
01:12:37.353 [Binder:3764_10] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0x4a 0x00 0x6f 0
x5f 0x00 0xde 0xff 0x00 0x00 0x06 0x6f 0xc4 0x01 0xde 0xff 0x00 0x00
01:12:37.357 [Binder:3764_10] WARN  n.f.g.s.d.h.m.o.FetchSportsDetailsOperation - sports details: 0x4a 0x00 0x6f 0x5f 0x00 0xde 0xff 0x00 0x00
 0x06 0x6f 0xc4 0x01 0xde 0xff 0x00 0x00
01:12:37.365 [Binder:3764_10] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0x4c 0x00 0x71 0
x55 0x00 0xea 0xff 0x00 0x00 0x06 0x71 0xc5 0x01 0xea 0xff 0x00 0x00
01:12:37.369 [Binder:3764_10] WARN  n.f.g.s.d.h.m.o.FetchSportsDetailsOperation - sports details: 0x4c 0x00 0x71 0x55 0x00 0xea 0xff 0x00 0x00
 0x06 0x71 0xc5 0x01 0xea 0xff 0x00 0x00
01:12:37.388 [Binder:3764_10] ERROR n.f.g.u.GB - Error fetching sport details, invalid package counter: 76, last was: 74
01:12:37.390 [Binder:3764_10] INFO  n.f.g.s.d.h.m.o.FetchSportsDetailsOperation - fetching sport details has finished round 1
01:12:37.400 [Binder:3764_10] INFO  n.f.g.i.GBDevice - Mark device as NOT busy anymore: Rufe Aktivitätsdaten ab
01:12:37.402 [Binder:3764_10] DEBUG n.f.g.s.b.BtLEQueue - about to add: 01:12:37: Transaction task: reenabling disabled notifications with 2 a
ctions
01:12:37.407 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 9. Juli, 01:12: NotifyAction on characteristic: 0
0000004-0000-3512-2118-0009af100700
01:12:37.410 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.NotifyAction - use NOTIFICATION
01:12:37.442 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
01:12:37.458 [Binder:3764_10] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0x4d 0x00 0x72 0
x5a 0x00 0xe2 0xff 0x00 0x00 0x06 0x72 0xc4 0x01 0xe2 0xff 0x00 0x00
01:12:37.461 [Binder:3764_10] INFO  n.f.g.s.d.h.m.MiBand2Support - Unhandled characteristic changed: 00000005-0000-3512-2118-0009af100700
01:12:37.466 [Binder:3764_10] INFO  n.f.g.s.d.h.a.AmazfitBipSupport - RECEIVED DATA WITH LENGTH: 17
01:12:37.466 [Binder:3764_10] WARN  n.f.g.s.d.h.a.AmazfitBipSupport - DATA: 4D00725A00E2FF00000672C401E2FF0000
01:12:37.487 [Binder:3764_10] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0x4f 0x06 0x73 0xc4 0x01 0xe0 0xff 0x00 0x00 0x00 0x74 0x4b 0x00 0xf0 0xff 0x00 0x00
01:12:37.488 [Binder:3764_10] INFO  n.f.g.s.d.h.m.MiBand2Support - Unhandled characteristic changed: 00000005-0000-3512-2118-0009af100700
01:12:37.488 [Binder:3764_10] INFO  n.f.g.s.d.h.a.AmazfitBipSupport - RECEIVED DATA WITH LENGTH: 17
01:12:37.488 [Binder:3764_10] WARN  n.f.g.s.d.h.a.AmazfitBipSupport - DATA: 4F0673C401E0FF000000744B00F0FF0000
01:12:37.507 [Binder:3764_10] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0x51 0x06 0x75 0xc5 0x01 0xe1 0xff 0x00 0x00 0x00 0x76 0x50 0x00 0xec 0xff 0x00 0x00

#### Your wearable device is:

Amazfit Bip
FW: 1.0.1.00
HW: V0.11.2.4

*Please specify model and firmware version if possible*

#### Your android version is:
LOS 14.1

#### Your Gadgetbridge version is:
0.27.1

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by dazzzl** [comment]
Unfortunately, this issue still exists in GB 0.30.0. No activity can be downloaded which has a certain amount of size. 
I have the feeling that firmware uploading has been improved, but not downloading of activities.

**Comment by dazzzl** [comment]
This issue still exists in the latest GB version. This makes GB unusable for recording longer tracks. I think, this error could be handled with less effort. Possible solution: 
a) Ignore the error and remove the erroneous way points in the GPX.  
b) retransfer the erroneous data.

**Comment by ashimokawa** [comment]
Most probably your phone's Bluetooth stack is broken.

We have never experienced packet loss on any phone. Because it is not reproducible here I have no idea how to test possible fixes. 🤔

**Comment by TaaviE** [comment]
What phone are you using? It might be a good idea to warn potential users against potential broken BT stack on that HW+SW.

**Comment by dazzzl** [comment]
Sorry, for the late response:
It is a sony xperia M (nicki) with Lineageos 14.1 
Firmware updates are fine but not the transfer of the activities. Hpwever, I think the firmware updates are done in a more reliable way. Maybe we can use this also to transfer the activities?

**Comment by dazzzl** [comment]
So, I now know what is going on. I have the following error:

`10-09 19:39:17.717  3599  3611 W nodomain.freeyourgadget.gadgetbridge.service.devices.huami.operations.FetchSportsDetailsOperatsports details: 0x18 0x00 0x70 0xb6 0xff 0x38 0x00 0x00 0x00 0x06 0x70 0x73 0x01 0x38 0x00 0x00 0x00

10-09 19:39:17.721  3599  3611 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0x19 0x00 0x71 0xa2 0xff 0x40 0x00 0x00 0x00 0x06 0x71 0x73 0x01 0x40 0x00 0x00 0x00

10-09 19:39:17.724  3599  3611 W nodomain.freeyourgadget.gadgetbridge.service.devices.huami.operations.FetchSportsDetailsOperatsports details: 0x19 0x00 0x71 0xa2 0xff 0x40 0x00 0x00 0x00 0x06 0x71 0x73 0x01 0x40 0x00 0x00 0x00

10-09 19:39:17.727  1005  1094 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 160)

10-09 19:39:17.734  1005  1094 E BluetoothServiceJni: An exception was thrown by callback 'btgattc_notify_cb'.

10-09 19:39:17.734  1005  1094 E BluetoothServiceJni: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died

10-09 19:39:17.734  1005  1094 E BluetoothServiceJni:   at android.os.BinderProxy.transactNative(Native Method)

10-09 19:39:17.734  1005  1094 E BluetoothServiceJni:   at android.os.BinderProxy.transact(Binder.java:617)

10-09 19:39:17.734  1005  1094 E BluetoothServiceJni:   at android.bluetooth.IBluetoothGattCallback$Stub$Proxy.onNotify(IBluetoothGattCallback.java:413)

10-09 19:39:17.734  1005  1094 E BluetoothServiceJni:   at com.android.bluetooth.gatt.GattService.onNotify(GattService.java:855)

10-09 19:39:17.734  3599  3611 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0x1a 0x00 0x72 0x96 0xff 0x46 0x00 0x00 0x00 0x06 0x72 0x71 0x01 0x46 0x00 0x00 0x00
`

According to:

https://github.com/NordicSemiconductor/Android-BLE-Library/issues/85

it can only fixed in the application. Do you think you can do something?

Thanks!
