### ISSUE TITLE
Pebble Time disconnects on incoming notification (BufferOverflowException)

### ISSUE THREAD

**Issue by evll** [Freeyourgadget/Gadgetbridge#1323]
### Your issue is:
After updating to 0.31.0 most of the time when a notification is incoming, my Pebble Time disconnects. In the log I can see this exception:
```
09:01:59.867 [main] ERROR n.f.g.LoggingExceptionHandler - Uncaught exception: Unable to start service nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService@6a6ede0 with Intent { act=nodomain.freeyourgadget.gadgetbridge.devices.action.notification cmp=nodomain.freeyourgadget.gadgetbridge/.service.DeviceCommunicationService (has extras) }: java.nio.BufferOverflowException
java.lang.RuntimeException: Unable to start service nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService@6a6ede0 with Intent { act=nodomain.freeyourgadget.gadgetbridge.devices.action.notification cmp=nodomain.freeyourgadget.gadgetbridge/.service.DeviceCommunicationService (has extras) }: java.nio.BufferOverflowException
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3821) ~[na:0.0]
	at android.app.ActivityThread.access$1800(ActivityThread.java:207) ~[na:0.0]
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1779) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:193) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6863) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) ~[na:0.0]
Caused by: java.nio.BufferOverflowException: null
	at java.nio.Buffer.nextPutIndex(Buffer.java:536) ~[na:0.0]
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:144) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol.encodeNotification(PebbleProtocol.java:979) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol.encodeNotification(PebbleProtocol.java:509) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.service.serial.AbstractSerialDeviceSupport.onNotification(AbstractSerialDeviceSupport.java:118) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleSupport.onNotification(PebbleSupport.java:187) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.service.ServiceDeviceSupport.onNotification(ServiceDeviceSupport.java:152) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService.handleAction(DeviceCommunicationService.java:394) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService.onStartCommand(DeviceCommunicationService.java:347) ~[na:0.0]
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3802) ~[na:0.0]
```
[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/2556331/gadgetbridge.log)

#### Your wearable device is:

Pebble Time FW: v4.3 HW: snowy_dvt

#### Your android version is:

9 (OxygenOS 9.0.2 from OnePlus)

#### Your Gadgetbridge version is:

0.31.0

**Comment by evll** [comment]
Reverting to 0.30.0 makes the error go away, so I am staying on the older version for now.

**Comment by danielegobbetti** [comment]
@evll thanks for reporting this issue, it is indeed a race condition.

If you add at least one canned reply (settings -> pebble -> replies) everything should work on 0.31

**Comment by IzzySoft** [comment]
Thanks for mentioning the work-around, @danielegobetti – that explains why I don't see the issue with my Pebble time (1 canned response configured, though mostly unused). So this is an indirect confirmation the work-around works around :wink:
