### ISSUE TITLE
can Gadgetbride and Pebble app coexist ?

### ISSUE THREAD

**Issue by dnastase** [Freeyourgadget/Gadgetbridge#1359]
This is actually a question: can Gadgetbrige and the Pebble app be installed at the same time ?

I'm asking this because:
- I had Gadgetbridge installed and working super nice for a looong time with my Pebble 2 SE
- then I bought another Pebble 2 SE and I wanted to play w/ the Pebble/Rebble so I connected like that (so watch1 connected to Gadgetbridge and watch2 to Pebble, total separation)
- not to wear two watches I temporarily disabled my first watch's bluetooth
- after not even a day I wanted to re-enable the use of my first watch and it just wouldn't connect
- anything I tried to make it connect (unpair, re-install Gadget bridge, reboot both phone and watch, etc) it just didn't connect ...
- it only connected back when I uninstalled the Pebble app ...

**Comment by dnastase** [comment]
Snapshot of the relevant part of the log:

```
06:53:26.023 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.26.5
06:53:32.498 [main] INFO  n.f.g.a.ControlCenterv2 - onResume
06:53:34.172 [Thread-7] INFO  n.f.g.s.d.p.PebbleIoThread - init connect: Trying to connect (attempts left 7)
06:53:34.180 [Thread-7] INFO  n.f.g.s.d.p.PebbleIoThread - This is a Pebble 2 or Pebble-LE/Pebble Time LE, will use BLE
06:53:34.211 [Binder:22539_4] INFO  n.f.g.s.d.p.b.PebbleLESupport - unhandled device: 58:46:5A:7F:ED:FC , ignoring, will only talk to 7F:3C:D4:A1:BC:96
06:53:34.221 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTServer - onServiceAdded() status = 0 service = 10000000-328e-0fbb-c642-1aa6699bdada
06:53:34.228 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTServer - onServiceAdded() status = 0 service = badbadba-dbad-badb-adba-badbadbadbad
06:53:34.335 [main] WARN  n.f.g.i.GBDeviceCandidate - no cached services available for Pebble C480: 7F:3C:D4:A1:BC:96 (UNKNOWN)
06:53:34.345 [main] WARN  n.f.g.i.GBDeviceCandidate - no cached services available for Pebble C480: 7F:3C:D4:A1:BC:96 (UNKNOWN)
06:53:34.730 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
06:53:34.738 [main] INFO  n.f.g.e.NotificationListener - ignoring StatusBarNotification from nodomain.freeyourgadget.gadgetbridge
06:53:35.214 [Thread-7] INFO  n.f.g.s.d.p.b.PebbleGATTClient - bef btDevice.connectGatt
06:53:35.227 [Thread-7] INFO  n.f.g.s.d.p.b.PebbleGATTClient - aft btDevice.connectGatt
06:53:36.210 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTServer - Connection state change for device: 7F:3C:D4:A1:BC:96  status = 0 newState = 2
06:53:36.233 [main] INFO  n.f.g.e.BluetoothConnectReceiver - connection attempt detected from or to 7F:3C:D4:A1:BC:96(Pebble C480)
06:53:36.248 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - onConnectionStateChange() status = 0 newState = 2
06:53:36.250 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - calling discoverServices()
06:53:36.261 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - onServicesDiscovered() status = 0
06:53:36.264 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - This seems to be a >=4.0 FW Pebble, writing to pairing trigger
06:53:36.615 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - subscribing to connection parameters characteristic
06:53:36.707 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - onCharacteristicChanged()00000005-328e-0fbb-c642-1aa6699bdada 0024000000F401
06:53:36.749 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - onDescriptorWrite() status=0
06:53:36.751 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - subscribing to connectivity characteristic
06:53:36.841 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - onCharacteristicChanged()00000001-328e-0fbb-c642-1aa6699bdada 1F000000
06:53:36.845 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - onDescriptorWrite() status=0
06:53:36.848 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - subscribing to mtu characteristic
06:53:36.931 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - Pebble requested MTU: 23
06:53:36.973 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - onDescriptorWrite() status=0
06:53:36.975 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - setting MTU
06:53:37.155 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTServer - Pebble requested mtu for server: 339
06:53:37.200 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - Pebble requested MTU: 339
06:53:37.291 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - Pebble requested MTU: 339
06:53:41.864 [Binder:22539_4] INFO  n.f.g.s.d.p.b.PebbleGATTClient - onCharacteristicChanged()00000005-328e-0fbb-c642-1aa6699bdada 000C0000005802
06:53:52.695 [Binder:22539_1] INFO  n.f.g.s.d.p.b.PebbleGATTClient - onCharacteristicChanged()00000005-328e-0fbb-c642-1aa6699bdada 009C0000005802
06:54:05.247 [Thread-7] INFO  n.f.g.s.d.p.b.PebbleGATTClient - PebbleGATTClient.close
06:54:05.268 [Thread-7] WARN  n.f.g.s.d.p.PebbleIoThread - error while connecting: connection failed
java.io.IOException: connection failed
        at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.ble.PebbleLESupport.<init>(PebbleLESupport.java:85) ~[na:0.0]
        at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread.connect(PebbleIoThread.java:191) ~[na:0.0]
        at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread.run(PebbleIoThread.java:260) ~[na:0.0]
06:54:05.449 [main] WARN  n.f.g.i.GBDeviceCandidate - no cached services available for Pebble C480: 7F:3C:D4:A1:BC:96 (UNKNOWN)
06:54:05.456 [main] WARN  n.f.g.i.GBDeviceCandidate - no cached services available for Pebble C480: 7F:3C:D4:A1:BC:96 (UNKNOWN)
06:54:05.794 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
06:54:05.801 [main] INFO  n.f.g.e.NotificationListener - ignoring StatusBarNotification from nodomain.freeyourgadget.gadgetbridge
06:54:22.273 [Thread-7] INFO  n.f.g.s.d.p.PebbleIoThread - init connect: Trying to connect (attempts left 6)
```

**Comment by ashimokawa** [comment]
@dnastase 
I never used the official app but I *think* they can't co-exist in case of Pebble 2. 
I can do tests when my Pebble 2 works again
See  #1340

**Comment by jumper047** [comment]
I have two PT, one of them connected to official pebble app, and another - to gadgetbridge. All works fine. LinageOS 15.1 if that matter

**Comment by IzzySoft** [comment]
As jumper answered the question and there was no response from you anymore, the issue can IMHO be considered solved. If you don't share my opinion, just say so and give reasoning, and we'll reopen. That would require you updating your initial post, though (you've skipped the template): Android device and version might be relevant here.

Another hint along the lines: you could try to isolate the official app using e.g. [Shelter](https://f-droid.org/packages/net.typeblog.shelter/) if it gets in the way.
