### ISSUE TITLE
Merged database imported, but Pebble activity history crashes

### ISSUE THREAD

**Issue by lzmartinico** [Freeyourgadget/Gadgetbridge#1418]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*If possible, please attach [logs](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files)! that might help identifying the problem.*
I consolidated several old database files containing some Pebble Health data. The database was imported succesfully in the app, and the Pebble device appears; the health data is however inacessible, as the app crashes every time I try to open the graph. 
I tried to enable the log file, but it doesn't get written to disk; however I captured a log through logcat:
`FATAL EXCEPTION: main
Process: nodomain.freeyourgadget.gadgetbridge, PID: 28141
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
	at nodomain.freeyourgadget.gadgetbridge.util.PebbleUtils.getPlatformName(PebbleUtils.java:39)
	at nodomain.freeyourgadget.gadgetbridge.util.PebbleUtils.hasHRM(PebbleUtils.java:75)
	at nodomain.freeyourgadget.gadgetbridge.devices.pebble.PebbleCoordinator.supportsHeartRateMeasurement(PebbleCoordinator.java:131)
	at nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractChartFragment.supportsHeartrate(AbstractChartFragment.java:115)
	at nodomain.freeyourgadget.gadgetbridge.activities.charts.ActivitySleepChartFragment.setupLegend(ActivitySleepChartFragment.java:174)
	at nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractChartFragment.configureChartDefaults(AbstractChartFragment.java:367)
	at nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractChartFragment.configureBarLineChartDefaults(AbstractChartFragment.java:371)
	at nodomain.freeyourgadget.gadgetbridge.activities.charts.ActivitySleepChartFragment.setupChart(ActivitySleepChartFragment.java:79)
	at nodomain.freeyourgadget.gadgetbridge.activities.charts.ActivitySleepChartFragment.onCreateView(ActivitySleepChartFragment.java:66)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
	at android.view.View.measure(View.java:20208)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:1007)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
	at android.view.View.measure(View.java:20208)
	at android.support.v4.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:622)
	at android.view.View.measure(View.java:20208)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6245)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
	at android.view.View.measure(View.java:20208)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6245)
	at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:400)
	at android.view.View.measure(View.java:20208)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6245)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
	at android.view.View.measure(View.java:20208)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6245)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1705)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:797)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
	at android.view.View.measure(View.java:20208)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6245))
`
#### Your wearable device is:
Pebble 2 HR
*Please specify model and firmware version if possible*

#### Your android version is:
7.1.1
#### Your Gadgetbridge version is:

0.32.1

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by vanous** [comment]
Hello, as you mentioned, most probably the issue was caused by the merge itself. Were you able to solve this and can this issue be closed now? thank you

**Comment by lzmartinico** [comment]
No, I could never succesfully use the merged database. From what I can tell, a change in the device table wasn't being propagated to the GBDevice object, which causes the activity graph to crash because of a missing value. It would be nice to have some additional guidance in the Wiki on how to debug such a crash (e.g. how to update the GBDevice object when importing a new database)

**Comment by vanous** [comment]
I have done this without any issue (on MiBand) and have documented it here: https://github.com/Freeyourgadget/Gadgetbridge/wiki/Data-Export-Import-Merging-Processing#merge-data-from-old-gadgetbridge-export

**Comment by lzmartinico** [comment]
I followed a very similar approach, so it would be nice if there was
some info on failure scenarios and how to debug them. Obviously I
realise that it's very hard to reproduce, and I wish I could give you
some info on why my failure has occurred. As you reminded me of this
issue after a few months, I had a look at the database again and it
seems like having multiple devices in the new database might be causing
some issues (the _id field of my pebble didn't match between the devices
table and the health table), but having corrected the obvious fault I
still have the same problem. It would be good though if the wiki explained inconsistencies
such as this to keep an eye out for in the migration section!

vanous writes:

> I have done this without any issue (on MiBand) and have documented it here: https://github.com/Freeyourgadget/Gadgetbridge/wiki/Data-Export-Import-Merging-Processing#merge-data-from-old-gadgetbridge-export

**Comment by vanous** [comment]
:) feel free to explore this further and document your findings!
