### ISSUE TITLE
Gadgetbridge crashes on opening Sleep statistics

### ISSUE THREAD

**Issue by hkemal** [Freeyourgadget/Gadgetbridge#1428]
#### Before reporting a bug, please confirm the following:
- [x ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*If possible, please attach [logs](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files)! that might help identifying the problem.*

#### Your wearable device is:
Mi Band 3 FW 2.3.0.2

#### Your android version is:
LineageOS 15.1 current nightly

#### Your Gadgetbridge version is:
0.32.2

Hello,

yesterday I updated to the newest Gadgetbride version from F-Droid. Since then the app crashes if I want to check my Sleep statitics under activites.

Attached the relevant part of the log file:

08:33:00.083 [Binder:13046_1] INFO  n.f.g.s.d.h.o.FetchActivityOperation - Mi2 activity data: last sample timestamp: 15. Februar, 08:33
08:33:00.084 [Binder:13046_1] INFO  n.f.g.s.d.h.o.FetchActivityOperation - Hopefully no further fetch needed, last synced timestamp is from today.
08:33:00.086 [Binder:13046_1] INFO  n.f.g.i.GBDevice - Mark device as NOT busy anymore: Aktivitätsdaten abrufen
08:33:00.087 [Binder:13046_1] DEBUG n.f.g.s.b.BtLEQueue - about to add: 08:33:00: Transaction task: reenabling disabled notifications with 2 actions
08:33:00.089 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 15. Februar, 08:33: NotifyAction on characteristic: 00000004-0000-3512-2118-0009af100700
08:33:00.094 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.NotifyAction - use NOTIFICATION
08:33:00.098 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
08:33:00.119 [main] INFO  n.f.g.e.NotificationListener - Notification removed: nodomain.freeyourgadget.gadgetbridge: null
08:33:00.154 [Binder:13046_1] DEBUG n.f.g.s.b.BtLEQueue - descriptor write: 00002902-0000-1000-8000-00805f9b34fb (success)
08:33:00.158 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 15. Februar, 08:33: NotifyAction on characteristic: 00000005-0000-3512-2118-0009af100700
08:33:00.165 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.NotifyAction - use NOTIFICATION
08:33:00.244 [Binder:13046_1] DEBUG n.f.g.s.b.BtLEQueue - descriptor write: 00002902-0000-1000-8000-00805f9b34fb (success)
08:33:03.327 [AsyncTask #1] INFO  n.f.g.a.c.AbstractChartFragment - Deine Aktivität und Schlaf: number of samples:1443
08:33:03.424 [AsyncTask #2] INFO  n.f.g.a.c.AbstractChartFragment - Dein Schlaf: number of samples:1443
08:33:05.063 [main] ERROR n.f.g.u.GB - Fehler beim Ausführen 'Conversion = 'End of String''
java.util.UnknownFormatConversionException: Conversion = 'End of String'
	at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2641) ~[na:0.0]
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2602) ~[na:0.0]
	at java.util.Formatter.parse(Formatter.java:2557) ~[na:0.0]
	at java.util.Formatter.format(Formatter.java:2504) ~[na:0.0]
	at java.util.Formatter.format(Formatter.java:2458) ~[na:0.0]
	at java.lang.String.format(String.java:2814) ~[na:0.0]
	at android.content.res.Resources.getString(Resources.java:458) ~[na:0.0]
	at androidx.fragment.app.Fragment.getString(Fragment.java:795) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.charts.WeekSleepChartFragment.getBalanceMessage(WeekSleepChartFragment.java:81) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractWeekChartFragment.refreshWeekBeforeData(AbstractWeekChartFragment.java:133) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractWeekChartFragment.refreshInBackground(AbstractWeekChartFragment.java:78) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractChartFragment$RefreshTask.doInBackground(AbstractChartFragment.java:651) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.database.DBAccess.doInBackground(DBAccess.java:46) ~[na:0.0]
	at android.os.AsyncTask$2.call(AsyncTask.java:333) ~[na:0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:0.0]
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
08:33:05.070 [main] ERROR n.f.g.LoggingExceptionHandler - Uncaught exception: Attempt to invoke virtual method 'nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractWeekChartFragment$DayData nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractWeekChartFragment$MyChartsData.getDayData()' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractWeekChartFragment$DayData nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractWeekChartFragment$MyChartsData.getDayData()' on a null object reference
	at nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractWeekChartFragment.updateChartsnUIThread(AbstractWeekChartFragment.java:88) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractChartFragment$RefreshTask.onPostExecute(AbstractChartFragment.java:662) ~[na:0.0]
	at android.os.AsyncTask.finish(AsyncTask.java:695) ~[na:0.0]
	at android.os.AsyncTask.-wrap1(Unknown Source:0) ~[na:0.0]
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:164) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6494) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) ~[na:0.0]

**Comment by holgis** [comment]
Same here on SM-G960f with Stock Android 9.0

**Comment by steffenl82** [comment]
Happens also for me. App crashes immediately when switching either to the "your sleep", "sleep per week", or "steps per week" tab. I'm at Android 7.1.2 and Gadgetbridge 0.32.2 with a Mi Band 2

**Comment by marstum** [comment]
I can also confirm this crash for a Xiaomi Mi8 lite with MiUI 10.2.2.0 and Gadgetbridge version 0.32.2 on Mi Band 3.

**Comment by cpfeiffer** [comment]
Sorry for the crash. It was a bad format string in the German translation, so as a workaround you can switch the language to e.g. English to avoid the crash until the next version is out.
