### ISSUE TITLE
Crashing when flash an amazfit bip watchface

### ISSUE THREAD

**Issue by sansanomir** [Freeyourgadget/Gadgetbridge#1488]
#### Your issue is:
Application crash when I try to install some custom watchface. I have an Amazfit Bip
#### Your wearable device is:

*Please specify model and firmware version if possible*

#### Your android version is:
Android 6.0 ZTE BLADE V7
#### Your Gadgetbridge version is:
0.32.4

Link:  [https://www.dropbox.com/s/nh2hzwmh33bgh37/gadgetbridge.log?dl=0](url)
Log:
`13:15:52.877 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 22 de abril 13:15: SetDeviceStateAction to INITIALIZED
13:15:52.914 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000003-0000-3512-2118-0009af100700 value: 0x10 0x06 0x0c 0x00 0x01
13:15:52.915 [Binder_3] INFO  n.f.g.s.d.h.o.InitOperation - Unhandled characteristic changed: 00000003-0000-3512-2118-0009af100700
13:15:52.916 [Binder_3] INFO  n.f.g.s.d.h.HuamiSupport - Unhandled characteristic changed: 00000003-0000-3512-2118-0009af100700
13:15:52.917 [Binder_3] INFO  n.f.g.s.d.h.a.AmazfitBipSupport - RECEIVED DATA WITH LENGTH: 5
13:15:52.920 [Binder_3] WARN  n.f.g.s.d.h.a.AmazfitBipSupport - DATA: 10060C0001
13:15:52.950 [Binder_2] INFO  n.f.g.e.NotificationListener - Ignore notification
13:15:52.952 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
13:15:52.966 [main] ERROR n.f.g.LoggingExceptionHandler - Uncaught exception: %s does not support ' '
java.util.FormatFlagsConversionMismatchException: %s does not support ' '
	at java.util.Formatter$FormatToken.checkFlags(Formatter.java:1361) ~[na:0.0]
	at java.util.Formatter.transform(Formatter.java:1442) ~[na:0.0]
	at java.util.Formatter.doFormat(Formatter.java:1081) ~[na:0.0]
	at java.util.Formatter.format(Formatter.java:1042) ~[na:0.0]
	at java.util.Formatter.format(Formatter.java:1011) ~[na:0.0]
	at java.lang.String.format(String.java:1554) ~[na:0.0]
	at android.content.res.Resources.getString(Resources.java:472) ~[na:0.0]
	at android.content.Context.getString(Context.java:430) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.devices.miband.AbstractMiBandFWInstallHandler.validateInstallation(AbstractMiBandFWInstallHandler.java:115) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.FwAppInstallerActivity.validateInstallation(FwAppInstallerActivity.java:123) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.FwAppInstallerActivity.access$400(FwAppInstallerActivity.java:55) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.FwAppInstallerActivity$1.onReceive(FwAppInstallerActivity.java:93) ~[na:0.0]
	at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313) ~[na:0.0]
	at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:111) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:207) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5728) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) ~[na:0.0]`

**Comment by segalion** [comment]
same problem. I have last firmware version 1,1,5,16, and samsung S5

**Comment by mjestebanez** [comment]
Same problem too. I have  firmware version 1.1.15.16,  lineageOs 13 and gadgetbridge 0.33.1

**Comment by ashimokawa** [comment]
Which language is your phone set to?

**Comment by sansanomir** [comment]
Application is in Spanish(system default). I've just changed application to English and It worked correctly.

**Comment by mjestebanez** [comment]
Spanish.



________________________________
De: Andreas Shimokawa <notifications@github.com>
Enviado: jueves, 6 de junio de 2019 12:14
Para: Freeyourgadget/Gadgetbridge
Cc: mjestebanez; Comment
Asunto: Re: [Freeyourgadget/Gadgetbridge] Crashing when flash an amazfit bip watchface (#1488)


Which language is your phone set to?

**Comment by ashimokawa** [comment]
Fixed in commit f959022cad6aa5da8b182d551526baa7c6d692ad, a typo during translation :(

Unfortunately Gadgetbridge 0.34.0 is already tagged, so this will land in 0.34.1
