### ISSUE TITLE
The application crashes the moment it is opened.

### ISSUE THREAD

**Issue by sargoon** [Freeyourgadget/Gadgetbridge#1496]
#### The issue is:
The application crashes the moment it is opened.
#### My wearable device is:
Samsung Galaxy S6 Edge

#### My android version is:
Android 7.0

#### My Gadgetbridge version is:
Gadgetbridge 0.32.4

Recording Of The Bug
https://thumbs.gfycat.com/FailingWetLiger-size_restricted.gif

**Comment by ashimokawa** [comment]
@sargoon 
Thanks for reporting.
Unfortunately we need logs, a video is a proof but does not help.
Could you provide the logs?

**Comment by sargoon** [comment]
You're welcome! Sure, here is the logs: https://pasteboard.co/IbOIMGgG.png

**Comment by sargoon** [comment]
Also, here is the logcat report (code form).

```
E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 5299): Uncaught exception: Unable to add window -- token android.os.BinderProxy@fe3efc7 is not valid; is your activity running?android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@fe3efc7 is not valid; is your activity running? E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 5299): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:679) ~[na:0.0] E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 5299): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342) ~[na:0.0] E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 5299): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93) ~[na:0.0] E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 5299): 	at android.widget.Toast$TN.handleShow(Toast.java:459) ~[na:0.0] E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 5299): 	at android.widget.Toast$TN$2.handleMessage(Toast.java:342) ~[na:0.0] E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 5299): 	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0] E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 5299): 	at android.os.Looper.loop(Looper.java:154) ~[na:0.0] E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 5299): 	at android.app.ActivityThread.main(ActivityThread.java:6169) ~[na:0.0] E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 5299): 	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0] E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 5299): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891) ~[na:0.0] E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 5299): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) ~[na:0.0] E/AndroidRuntime( 5299): Process: nodomain.freeyourgadget.gadgetbridge, PID: 5299

```
