### ISSUE TITLE
Crash on entering device settings after upgrade to 0.34.0

### ISSUE THREAD

**Issue by oldnomad** [Freeyourgadget/Gadgetbridge#1541]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
After upgrading from 0.33.1 to 0.34.0 there's a new icon for per-device settings. Clicking on the icon in my case results in the application crashing with ClassCastException. The stacktrace is:

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:283)
	at androidx.preference.Preference.getPersistedString(Preference.java:1686)
	at androidx.preference.EditTextPreference.onSetInitialValue(EditTextPreference.java:106)
	at androidx.preference.Preference.onSetInitialValue(Preference.java:1614)
	at androidx.preference.Preference.dispatchSetInitialValue(Preference.java:1587)
	at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1311)
	at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1326)
	at androidx.preference.PreferenceGroup.addPreference(PreferenceGroup.java:249)
	at androidx.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:170)
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:345)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:157)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:109)
	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216)
	at androidx.preference.PreferenceFragmentCompat.addPreferencesFromResource(PreferenceFragmentCompat.java:361)
	at nodomain.freeyourgadget.gadgetbridge.activities.devicesettings.DeviceSpecificSettingsFragment.onCreatePreferences(DeviceSpecificSettingsFragment.java:81)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2596)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:831)
	at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197)
	at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080)
	at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1853)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2650)
	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2600)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
	at android.app.Activity.performStart(Activity.java:7161)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2938)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:186)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:171)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

It seems that some setting that was integer in previous version is now interpreted as a string, and reading the old setting fails.

#### Your wearable device is:

Mi Band 1S, FW 4.16.11.15, HR 1.3.76.22

#### Your android version is:

Android 9

#### Your Gadgetbridge version is:

0.34.0 (upgraded from 0.33.1, upgraded from previous versions)

**Comment by ashimokawa** [comment]
@oldnomad
I can confirm that the issue exists on Mi Band 1S, not on others, and I will fix it asap.
