### ISSUE TITLE
Gadgetbridge crashes when updating the firmware of a Mi Band 2

### ISSUE THREAD

**Issue by 97carmine** [Freeyourgadget/Gadgetbridge#1577]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

Gadgetbridge crashes when updating to Mi Band 2 firmware.

I have already used the procedure previously with an HTC 10 and had no problems.

```
java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.util.Formatter.format(Formatter.java:2522)
	at java.util.Formatter.format(Formatter.java:2458)
	at java.lang.String.format(String.java:2883)
	at android.content.res.Resources.getString(Resources.java:478)
	at android.content.Context.getString(Context.java:603)
	at nodomain.freeyourgadget.gadgetbridge.devices.miband.AbstractMiBandFWInstallHandler.getFwUpgradeNotice(AbstractMiBandFWInstallHandler.java:66)
	at nodomain.freeyourgadget.gadgetbridge.devices.miband.AbstractMiBandFWInstallHandler.validateInstallation(AbstractMiBandFWInstallHandler.java:102)
	at nodomain.freeyourgadget.gadgetbridge.devices.huami.miband2.MiBand2FWInstallHandler.validateInstallation(MiBand2FWInstallHandler.java:46)
	at nodomain.freeyourgadget.gadgetbridge.activities.FwAppInstallerActivity.validateInstallation(FwAppInstallerActivity.java:123)
	at nodomain.freeyourgadget.gadgetbridge.activities.FwAppInstallerActivity.access$400(FwAppInstallerActivity.java:55)
	at nodomain.freeyourgadget.gadgetbridge.activities.FwAppInstallerActivity$1.onReceive(FwAppInstallerActivity.java:93)
	at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
	at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

#### Your wearable device is:

Mi Band 2: 
FW: 1.0.1.81 
HW: V0.1.3.2

#### Your android version is:

Xiaomi Pocophone - Android 9 (MIUI Global 10.3.6)

#### Your Gadgetbridge version is:

0.34.1

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by ashimokawa** [comment]
@97carmine 
Which language is Gadgetbridge set to?
Can you try English?

**Comment by 97carmine** [comment]
System default (Spanish), changing the language to english fix the issue.

Thanks.

**Comment by ashimokawa** [comment]
@97carmine 
Will be fixed in the next release

**Comment by sureshkodur** [comment]
Can anyone help me, how to update? I have the *.fw file in my mobile. and Gadgetbridge app also. But I dont know how to update? Plz help me
