### ISSUE TITLE
I can't delete device

### ISSUE THREAD

**Issue by giupardeb** [Freeyourgadget/Gadgetbridge#1605]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I added two device: Amazfitbip and mi band2. I want delete cardboard associated with miband2. When I click on the icon trash and then tap on "delete" button, nothing is happening. I  still see the cardboard's device.

#### Your Gadgetbridge version is: 0.35.2

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by ashimokawa** [comment]
@giupardeb 
Can you see if there is some error in the logs, I just deleted my mi band 2 successfully and cannot reproduce...

**Comment by giupardeb** [comment]
there is not any error in the logs...only this:

```
15:06:08.549 [main] ERROR n.f.g.LoggingExceptionHandler - Uncaught exception: file:///storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/gadgetbridge.log exposed beyond app through ClipData.Item.getUri()
android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/gadgetbridge.log exposed beyond app through ClipData.Item.getUri()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960) ~[na:0.0]
	at android.net.Uri.checkFileUriExposed(Uri.java:2356) ~[na:0.0]
	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:942) ~[na:0.0]
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9850) ~[na:0.0]
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9856) ~[na:0.0]
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9835) ~[na:0.0]
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1610) ~[na:0.0]
	at android.app.Activity.startActivityForResult(Activity.java:4487) ~[na:0.0]
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676) ~[na:0.0]
	at android.app.Activity.startActivityForResult(Activity.java:4445) ~[na:0.0]
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663) ~[na:0.0]
	at android.app.Activity.startActivity(Activity.java:4806) ~[na:0.0]
	at android.app.Activity.startActivity(Activity.java:4774) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.DebugActivity.shareLog(DebugActivity.java:334) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.DebugActivity.access$800(DebugActivity.java:67) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.DebugActivity$18.onClick(DebugActivity.java:305) ~[na:0.0]
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:164) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6494) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) ~[na:0.0]
```

**Comment by giupardeb** [comment]
@ashimokawa any news?

**Comment by ashimokawa** [comment]
@giupardeb 
No, if there were I would have posted them.
What you posted is not a log, only a log that the log could not be accessed. No idea why. Did you grant all permissions?

**Comment by giupardeb** [comment]
@ashimokawa 
YES, all permissions have been granted

**Comment by ashimokawa** [comment]
@giupardeb 
Then I can only guess and stare at the code.
Please try to get the log with 

`
adb pull storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/gadgetbridge.log
`
if you tried to get the above with the log sharing option

**Comment by giupardeb** [comment]
I can get log. This is the output:
```
adb pull storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/gadgetbridge.log
storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/gadgetbridge.log: 1 file pulled. 12.1 MB/s (723531 bytes in 0.057s)
```

**Comment by ashimokawa** [comment]
@giupardeb 
Yes, but only thje part that happens when you try to delete the mi band 2. The log may contain personal data, so it might not be good to paste it in public.

**Comment by giupardeb** [comment]
@ashimokawa 
sorry, But when I try to delete mi band2, nothing is written to the log.

**Comment by vanous** [comment]
OK, i think i have figured it out.

Long story short: accidental phone unlock in pocket resulted in (+) button press, first device was selected any my relative's band vibrated. Unfortunately, the press was confirmed, band paired to GB (normally used on another phone with MiFit), resulting in whole day data loss (don't worry, they will cope with that). The bigger issue was, that i could not get rid of the device. I have found few issues during the process:

1) when you empty the database, (Settings → Database management) and come back, the listing still shows all previously present devices (two in my case). Swipe GB away, come back - devices still present. Menu → Quit, re-open - devices still present.

back to this one device which cannot be deleted:

2) clean data/uninstall, re-import previous data causes GB to again, show this supposedly deleted device. Checked all database entries, no mention of this device, except the Alarm database had few rows with device_id:2.

3) finally, i also checked the Export_preference file and in there were few entries with the MAC address of this device to be deleted:

  <String name="development_miaddr">xx:xx:...</String>
  <String name="last_device_address">xx:xx:...</String>

After deleting these and re-import:

4) after re.import, still no data in GB. You must kill GB in app → info → Force Stop, then re-start it, then it works.

5) perhaps, when a device is already paired, we could only keep "Add device" in the Menu...

cheers

**Comment by olgabaranov** [comment]
Same problem here (with MiBand 2 and Amazfit BIP, MiBand2 is not beging deleted). Nothing is written in the logs

**Comment by vanous** [comment]
Try this: look at the offending device, remember it's address, export database, edit the Export_preference and remove lines with the address you previously noted. empty database, restart application, make sure no device is in. if no help, clean application data/cache, then restart it. then re-import the database.

Keep backups from the /files folder to prevent data loss.

**Comment by olgabaranov** [comment]
Well, I nuked it while trying, which is in itself not a big deal. Though I've noticed that after I deleted the DB from inside GB the undeletable MiBand was still in the list while Bip wasn't. After deleting cache an data it was gone too

**Comment by vanous** [comment]
Sorry to hear about data loss. 

>undeletable MiBand was still in the list while Bip wasn't.

Yes, this is because the device is in preferences and not in the database.

**Comment by giupardeb** [comment]
is there a easy solution on the new GB version?

**Comment by vanous** [comment]
@ashimokawa 

i think that this should do: https://github.com/Freeyourgadget/Gadgetbridge/pull/1626 but i do not have another device now, so will try in near future.

**Comment by vanous** [comment]
ok, i have tested https://github.com/Freeyourgadget/Gadgetbridge/pull/1626 , added a little fix and it works for me. @giupardeb you can use this [PR](https://github.com/Freeyourgadget/Gadgetbridge/pull/1626) to test if you want to..., it is ready for merge.

**Comment by giupardeb** [comment]
Thank you @vanous  for your work, I needed to reset the phone so I can't test your fix :(. But I believe that PR works fine
