### ISSUE TITLE
java.lang.IllegalStateException in GBApplication.onCreate

### ISSUE THREAD

**Issue by B-HAL9000** [Freeyourgadget/Gadgetbridge#1639]
Finally Android build tools were fixed for me and Google reviewed the update I could release a new update on Google Play. Thus I have seen a few new crashes that most likely also affect vanilla GB that doesn't have the package name changed.

#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6227)
  at android.app.ActivityThread.access$1200 (ActivityThread.java:237)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1785)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7050)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
Caused by: java.lang.IllegalStateException: 
  at android.app.ContextImpl.startServiceCommon (ContextImpl.java:1666)
  at android.app.ContextImpl.startService (ContextImpl.java:1611)
  at android.content.ContextWrapper.startService (ContextWrapper.java:677)
  at ee.aegrel.gadgetbridge.GBApplication.onCreate (GBApplication.java:209)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1154)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6222)
  at android.app.ActivityThread.access$1200 (ActivityThread.java:237)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1785)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7050)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
```
Same crash with a bit different line numbers:
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6158)
  at android.app.ActivityThread.access$1200 (ActivityThread.java:235)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1768)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:6981)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)
Caused by: java.lang.IllegalStateException: 
  at android.app.ContextImpl.startServiceCommon (ContextImpl.java:1666)
  at android.app.ContextImpl.startService (ContextImpl.java:1611)
  at android.content.ContextWrapper.startService (ContextWrapper.java:677)
  at ee.aegrel.gadgetbridge.GBApplication.onCreate (GBApplication.java:209)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1154)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6153)
  at android.app.ActivityThread.access$1200 (ActivityThread.java:235)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1768)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:6981)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)
```

#### Your android version is:
9.0 or 10.0

#### Your Gadgetbridge version is:
36010229ee975c8cbfac6bc3743d7af0b287e266

**Comment by ashimokawa** [comment]
Thanks for reporting, I wish I could reproduce.
The stack does not tell me anything - it is all android internal code :/
(Not saying I am innocent)

**Comment by TaaviEo** [comment]
Yep it's mostly internal code, though trying to find more information about the crash I found that some devices also report the error like this:
```
java.lang.RuntimeException: Unable to create application ee.aegrel.gadgetbridge.GBApplication: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=ee.aegrel.gadgetbridge/.service.NotificationCollectorMonitorService }: app is in background uid UidRecord{4f59e64 u0a159 SVC  idle change:uncached procs:1 seq(0,0,0)}
FATAL EXCEPTION: main
Process: ee.aegrel.gadgetbridge, PID: 18049
java.lang.RuntimeException: Unable to create application ee.aegrel.gadgetbridge.GBApplication: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=ee.aegrel.gadgetbridge/.service.NotificationCollectorMonitorService }: app is in background uid UidRecord{4f59e64 u0a159 SVC  idle change:uncached procs:1 seq(0,0,0)}
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
  at android.app.ActivityThread.access$1100(ActivityThread.java:199)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:193)
  at android.app.ActivityThread.main(ActivityThread.java:6669)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=ee.aegrel.gadgetbridge/.service.NotificationCollectorMonitorService }: app is in background uid UidRecord{4f59e64 u0a159 SVC  idle change:uncached procs:1 seq(0,0,0)}
  at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
  at android.app.ContextImpl.startService(ContextImpl.java:1532)
  at android.content.ContextWrapper.startService(ContextWrapper.java:664)
  at ee.aegrel.gadgetbridge.GBApplication.onCreate(GBApplication.java:30)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
  ... 8 more
```

I suspect it's the same issue but Google Play shows it separate from the first for some reason.

**Comment by ashimokawa** [comment]
@TaaviEo 
Any idea which android variant they are on exactly?

**Comment by TaaviEo** [comment]
Galaxy S8 (dreamlte) | 189 | 5.3%
-- | -- | --
Mi A1 (tissot_sprout) | 160 | 4.5%
Mi A2 (jasmine_sprout) | 131 | 3.7%
Galaxy Note8 (greatlte) | 122 | 3.4%
Galaxy S10+ (beyond2) | 109 | 3.0%
Mi A2 Lite (daisy_sprout) | 108 | 3.0%
Galaxy S9+ (star2lte) | 107 | 3.0%
Galaxy S8+ (dream2lte) | 106 | 3.0%
Galaxy A50 (a50) | 101 | 2.8%
Galaxy Note9 (crownlte) | 89 | 2.5%
Pixel 2 (walleye) | 78 | 2.2%
OnePlus 6 (OnePlus6) | 74 | 2.1%
Galaxy Note10+ (d2q) | 71 | 2.0%
Galaxy A7 (2018) (a7y18lte) | 69 | 1.9%
OnePlus5 (OnePlus5) | 66 | 1.8%
Galaxy Note9 (crownlteks) | 62 | 1.7%
LG V50 ThinQ (flashlmdd) | 55 | 1.5%
Galaxy S10 (beyond1) | 54 | 1.5%
Galaxy J6 (j6lte) | 53 | 1.5%
Galaxy S10 5G (beyondx) | 49 | 1.4%
Others | 1,733 | 48.3%

**Comment by TaaviEo** [comment]
Seems fairly vendor-agnostic. I haven't personally neither encountered or managed to reproduce this bug which is annoying.

**Comment by IzzySoft** [comment]
Reading `Not allowed to start service Intent { … }: app is in background` and seeing devices are running Android 9+ – could this be something with `android.permission.FOREGROUND_SERVICE` not properly "requested" in some context? I see the permission was added with the last update of TaaviEo's version at Play (and wasn't there with the previous one). But then, the F-Droid version must have seen that for some time as well. Maybe it's something "silent" the user doesn't "see" or even notice?

What issues could that result in? I've just looked, we've got 151 open issues mentioning "notification" one way or the other, but I see nothing springing to the eye on the first result page (picked that term because of `ee.aegrel.gadgetbridge/.service.NotificationCollectorMonitorService`, but might have misinterpreted it here).

Just thinking aloud. If I'm not helpful with that, simply tell me to shut up and I will – no bad feelings :wink:

**Comment by TaaviEo** [comment]
> and seeing devices are running Android 9+

There are some rare cases of a similar stacktrace being thrown on 8.0 and 8.1, but I can't be sure it's the same, the long exception string is missing from those :/

**Comment by ashimokawa** [comment]
in commit 18157daf, the NotificationCollectorMonitorService was added that was before Gadgetbridge 0.19.0, see the commit log for its purpose.

**Comment by IzzySoft** [comment]
Thanks for clarification, @ashimokawa – so then it's no recent change having caused that, but rather newer Android versions. And given its purpose, most of these crashes probably go unnoticed from the user (unless someone happens to investigate logcat and stumbles upon them – or notifications suddenly stopping).

I'm not sure with which exact version Doze was getting harder on background stuff. It was somewhere after Nougat, but latest at Pie. Could well have been Oreo, so those 8.x cases might fit in here.

**Comment by joper30** [comment]
tablet android 8  gama baja is crash 40 bands 3 conected
