### ISSUE TITLE
0.6.6. Crash on opening

### ISSUE THREAD

**Issue by simonvanderveldt** [Freeyourgadget/Gadgetbridge#167]
After #166 happened I enabled debugging and tried a reboot of the phone. After doing so I am no longer able to open Gadgetbridge, it immediately crashes on opening.

This is the logcat:
```
shell@jgedlte:/ $ logcat * | grep -i gadgetbridge
I/ActivityManager(  974): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=nodomain.freeyourgadget.gadgetbridge/.activities.ControlCenter bnds=[0,1393][216,1722] (has extras)} from pid 1428
I/ActivityManager(  974): Start proc nodomain.freeyourgadget.gadgetbridge for activity nodomain.freeyourgadget.gadgetbridge/.activities.ControlCenter: pid=5305 uid=10156 gids={50156, 3002, 3001, 1028}
E/cutils  (  288): Failed to mkdirat(/storage/extSdCard/Android/data/nodomain.freeyourgadget.gadgetbridge): Read-only file system
W/ContextImpl( 5305): Failed to ensure directory: /storage/extSdCard/Android/data/nodomain.freeyourgadget.gadgetbridge/files
I/FileUtils( 5305): ignoring non-writable external storage dir: /storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files
E/AndroidRuntime( 5305): Process: nodomain.freeyourgadget.gadgetbridge, PID: 5305
E/AndroidRuntime( 5305): java.lang.RuntimeException: Unable to create application nodomain.freeyourgadget.gadgetbridge.GBApplication: java.lang.NullPointerException
E/AndroidRuntime( 5305): 	at nodomain.freeyourgadget.gadgetbridge.util.FileUtils.getWritableExternalFilesDirs(FileUtils.java:100)
E/AndroidRuntime( 5305): 	at nodomain.freeyourgadget.gadgetbridge.util.FileUtils.getExternalFilesDir(FileUtils.java:52)
E/AndroidRuntime( 5305): 	at nodomain.freeyourgadget.gadgetbridge.GBApplication.setupLogging(GBApplication.java:88)
E/AndroidRuntime( 5305): 	at nodomain.freeyourgadget.gadgetbridge.GBApplication.onCreate(GBApplication.java:58)
W/ActivityManager(  974):   Force finishing activity nodomain.freeyourgadget.gadgetbridge/.activities.ControlCenter
W/ActivityManager(  974): Activity pause timeout for ActivityRecord{436d3488 u0 nodomain.freeyourgadget.gadgetbridge/.activities.ControlCenter t2 f}
I/ActivityManager(  974): Process nodomain.freeyourgadget.gadgetbridge (pid 5305) has died.
```

I no longer have an SD card in the phone, so it definitely shouldn't be trying to use `/storage/extSdCard` :P

**Comment by cpfeiffer** [comment]
Thanks for the report, Simon!
