### ISSUE TITLE
Pebble: Crash on pressing watch button to end call

### ISSUE THREAD

**Issue by AluminumTank** [Freeyourgadget/Gadgetbridge#1727]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

### I got Gadgetbridge from:
* [x] F-Droid
* [ ] I built it myself from source code (specify tag / commit)

If you got it from Google Play, please note [that version](https://github.com/TaaviE/Gadgetbridge) is unofficial and not supported here; it's also often quite outdated. Please switch to one of the above versions if you can.

#### Your issue is:
*If possible, please attach [logs](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files)! that might help identifying the problem.*

Whenever I have an incoming call that I decline by pressing the "X" button on my watch, Gadgetbridge crashes and my watch disconnects.

Log:
```
16:35:59.349 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.39.0
16:35:59.392 [main] INFO  n.f.g.u.GB - Loading apps_notification_blacklist
16:35:59.393 [main] INFO  n.f.g.u.GB - Loaded apps_notification_blacklist has 0 entries
16:35:59.394 [main] INFO  n.f.g.u.GB - Loading apps_pebblemsg_blacklist
16:35:59.394 [main] INFO  n.f.g.u.GB - Loaded apps_pebblemsg_blacklist has 0 entries
16:35:59.395 [main] INFO  n.f.g.u.GB - Loading calendars_blacklist
16:35:59.395 [main] INFO  n.f.g.u.GB - Loaded calendars_blacklist has 0 entries
16:35:59.679 [main] INFO  n.f.g.s.NotificationCollectorMonitorService - ensureCollectorRunning collectorComponent: ComponentInfo{nodomain.freeyourgadget.gadgetbridge/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener}
16:35:59.680 [main] WARN  n.f.g.s.NotificationCollectorMonitorService - ensureCollectorRunning service - pid: 28686, currentPID: 28686, clientPackage: android, clientCount: 1, clientLabel: (Notification listener)
16:35:59.681 [main] DEBUG n.f.g.s.NotificationCollectorMonitorService - ensureCollectorRunning: collector is running
16:35:59.682 [main] DEBUG n.f.g.s.DeviceCommunicationService - DeviceCommunicationService is being created
16:35:59.683 [main] INFO  n.f.g.s.DeviceCommunicationService - no intent
16:35:59.690 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.start
16:35:59.694 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_deviceinfo
16:35:59.868 [main] INFO  n.f.g.e.NotificationListener - Ignore notification
16:36:12.647 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
16:36:12.702 [main] INFO  n.f.g.s.d.p.PebbleProtocol - setting always ACK PebbleKit to false
16:36:12.702 [main] INFO  n.f.g.s.d.p.PebbleProtocol - setting enable PebbleKit support to true
16:36:12.706 [Thread-2] INFO  n.f.g.s.d.p.PebbleIoThread - found service UUID 00001101-0000-1000-8000-00805f9b34fb
16:36:12.707 [Thread-2] INFO  n.f.g.s.d.p.PebbleIoThread - found service UUID 00000000-0000-1000-8000-00805f9b34fb
16:36:12.707 [Thread-2] INFO  n.f.g.s.d.p.PebbleIoThread - found service UUID 00000000-0000-1000-8000-00805f9b34fb
16:36:12.707 [Thread-2] INFO  n.f.g.s.d.p.PebbleIoThread - found service UUID 00000000-deca-fade-deca-deafdecacaff
16:36:12.741 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
16:36:12.761 [main] INFO  n.f.g.e.OmniJawsObserver - OmniJaws installation status: true
16:36:12.768 [main] INFO  n.f.g.e.OmniJawsObserver - OmniJaws is enabled: false
16:36:12.845 [main] INFO  n.f.g.e.NotificationListener - Ignore notification
16:36:13.720 [main] INFO  n.f.g.e.BluetoothConnectReceiver - connection attempt detected from or to B0:B4:48:A3:2E:1E(Pebble Time 2E1E)
16:36:13.945 [Thread-2] DEBUG n.f.g.s.d.p.PebbleIoThread - Not enabling background Webview, is disabled in preferences.
16:36:13.947 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - setting force protocol to false
16:36:14.063 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - Pebble asked for Phone/App Version - repLYING!
16:36:14.068 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
16:36:14.070 [main] INFO  n.f.g.e.OmniJawsObserver - OmniJaws installation status: true
16:36:14.076 [main] INFO  n.f.g.e.OmniJawsObserver - OmniJaws is enabled: false
16:36:14.171 [main] INFO  n.f.g.e.NotificationListener - Ignore notification
16:36:14.279 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - got LAUNCHER PUSH from UUID : 4368ffa4-f0fb-4823-90be-f754b076bdaa
16:36:14.381 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - Pebble firmware major detected as 4
16:36:14.382 [Thread-2] INFO  n.f.g.s.d.p.PebbleIoThread - syncing time
16:36:14.383 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - America/New_York
16:36:14.717 [Thread-2] INFO  n.f.g.s.AbstractDeviceSupport - Got event for VERSION_INFO: GBDeviceEventVersionInfo: fwVersion: v4.3; hwVersion: snowy_s3
16:36:14.746 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
16:36:14.749 [main] INFO  n.f.g.e.CalendarReceiver - Created calendar receiver.
16:36:14.750 [main] INFO  n.f.g.e.CalendarReceiver - got calendar changed broadcast
16:36:14.766 [main] INFO  n.f.g.e.CalendarReceiver - Syncing with calendar.
16:36:14.778 [main] INFO  n.f.g.e.OmniJawsObserver - OmniJaws installation status: true
16:36:14.782 [main] INFO  n.f.g.e.OmniJawsObserver - OmniJaws is enabled: false
16:36:14.820 [Thread-2] INFO  n.f.g.s.AbstractDeviceSupport - Got event for MUSIC_CONTROL
16:36:14.851 [main] INFO  n.f.g.e.NotificationListener - Ignore notification
16:36:14.923 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - DATALOG OPENSESSION. id=241, App UUID=00000000-0000-0000-0000-000000000000, log_tag=84, item_type=0, itemSize=26
16:36:14.925 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - sending ACK (0x85)
16:36:15.137 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - DATALOG OPENSESSION. id=187, App UUID=00000000-0000-0000-0000-000000000000, log_tag=79, item_type=0, itemSize=165
16:36:15.138 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - sending ACK (0x85)
16:36:15.340 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - DATALOG OPENSESSION. id=160, App UUID=00000000-0000-0000-0000-000000000000, log_tag=80, item_type=0, itemSize=36
16:36:15.341 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - sending ACK (0x85)
16:36:15.544 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - DATALOG OPENSESSION. id=116, App UUID=00000000-0000-0000-0000-000000000000, log_tag=78, item_type=0, itemSize=398
16:36:15.545 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - sending ACK (0x85)
16:36:15.757 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - DATALOG OPENSESSION. id=82, App UUID=00000000-0000-0000-0000-000000000000, log_tag=81, item_type=0, itemSize=249
16:36:15.758 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - sending ACK (0x85)
16:36:20.314 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.39.0
16:36:24.345 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.callstate
16:36:27.615 [Thread-2] INFO  n.f.g.s.AbstractDeviceSupport - Got event for CALL_CONTROL
16:36:27.634 [main] ERROR n.f.g.LoggingExceptionHandler - Uncaught exception: No interface method endCall()Z in class Lcom/android/internal/telephony/ITelephony; or its super classes (declaration of 'com.android.internal.telephony.ITelephony' appears in /system/framework/framework.jar!classes3.dex)
java.lang.NoSuchMethodError: No interface method endCall()Z in class Lcom/android/internal/telephony/ITelephony; or its super classes (declaration of 'com.android.internal.telephony.ITelephony' appears in /system/framework/framework.jar!classes3.dex)
	at nodomain.freeyourgadget.gadgetbridge.service.receivers.GBCallControlReceiver.onReceive(GBCallControlReceiver.java:51) ~[na:0.0]
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3788) ~[na:0.0]
	at android.app.ActivityThread.access$1400(ActivityThread.java:219) ~[na:0.0]
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:107) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:214) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:7356) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) ~[na:0.0]
```
#### Your wearable device is:
*Please specify model and firmware version if possible*

Pebble Time Steel
#### Your android version is:
Android 10

#### Your Gadgetbridge version is:
0.39.0

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by vanous** [comment]
I would suggests to provide Android flavor (vendor specific, CM, LOS...) or a device, i think it might be important here.

**Comment by AluminumTank** [comment]
Android Flavor is [ArrowOS](https://arrowos.net/) on a Moto G5 Plus (XT1687, codename: potter).
