### ISSUE TITLE
Incoming calls crash Gadgetbridge if permissions to access contacts are disabled on Android 6.0

### ISSUE THREAD

**Issue by haecker-felix** [Freeyourgadget/Gadgetbridge#182]
When I click Demo -> Incoming Call, the complete App crash.

**Comment by haecker-felix** [comment]
14:42:51.590 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.callstate
14:42:51.594 [main] ERROR n.f.g.LoggingExceptionHandler - Uncaught exception: Unable to start service nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService@1e079f8 with Intent { act=nodomain.freeyourgadget.gadgetbridge.devices.action.callstate cmp=nodomain.freeyourgadget.gadgetbridge/.service.DeviceCommunicationService (has extras) }: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{7496f42 3834:nodomain.freeyourgadget.gadgetbridge/u0a169} (pid=3834, uid=10169) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
java.lang.RuntimeException: Unable to start service nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService@1e079f8 with Intent { act=nodomain.freeyourgadget.gadgetbridge.devices.action.callstate cmp=nodomain.freeyourgadget.gadgetbridge/.service.DeviceCommunicationService (has extras) }: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{7496f42 3834:nodomain.freeyourgadget.gadgetbridge/u0a169} (pid=3834, uid=10169) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3027) ~[na:0.0]
	at android.app.ActivityThread.-wrap17(ActivityThread.java) ~[na:0.0]
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:148) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5417) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) ~[na:0.0]
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{7496f42 3834:nodomain.freeyourgadget.gadgetbridge/u0a169} (pid=3834, uid=10169) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
	at android.os.Parcel.readException(Parcel.java:1599) ~[na:0.0]
	at android.os.Parcel.readException(Parcel.java:1552) ~[na:0.0]
	at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3550) ~[na:0.0]
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:4778) ~[na:0.0]
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2018) ~[na:0.0]
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1468) ~[na:0.0]
	at android.content.ContentResolver.query(ContentResolver.java:475) ~[na:0.0]
	at android.content.ContentResolver.query(ContentResolver.java:434) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService.getContactDisplayNameByNumber(DeviceCommunicationService.java:433) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService.onStartCommand(DeviceCommunicationService.java:241) ~[na:0.0]
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010) ~[na:0.0]
	... 8 common frames omitted
14:42:53.360 [main] INFO  n.f.g.GBApplication - Gadgetbridge version: 0.6.7
14:42:53.425 [main] DEBUG n.f.g.s.DeviceCommunicationService - DeviceCommunicationService is being created
14:42:53.427 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.callstate
14:42:53.428 [main] INFO  n.f.g.s.DeviceCommunicationService - Must start service with nodomain.freeyourgadget.gadgetbridge.devices.action.start or nodomain.freeyourgadget.gadgetbridge.devices.action.connect before using it: nodomain.freeyourgadget.gadgetbridge.devices.action.callstate
14:42:53.428 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.start
14:42:53.433 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_deviceinfo

**Comment by ashimokawa** [comment]
@haecker-felix 
You have to grant access to contacts.

**Comment by ashimokawa** [comment]
This is for the reverse lookup of phone numbers, to display them on your pebble.
We should not crash when the user denies that permission in Android 6.0, accepted as bug ;)

**Comment by haecker-felix** [comment]
Okay it does works now.
