### ISSUE TITLE
Can't install any *.pbz or *.pbw from the download manager in Gadgetbridge 0.6.7 (regression)

### ISSUE THREAD

**Issue by haecker-felix** [Freeyourgadget/Gadgetbridge#183]
For example: https://dl.dropboxusercontent.com/u/6999250/dialer/PebbleDialer.pbw

-> pbw/pbz is broken or incompapatible with your Hardware or Firmware.

The App have all permissions.

Android 6.0
Nexus 5

15:24:44.388 [Binder_3] INFO  n.f.g.e.NotificationListener - Processing notification from source com.android.providers.downloads
15:24:44.398 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.notification
15:24:44.486 [Binder_3] INFO  n.f.g.e.NotificationListener - Processing notification from source com.android.providers.downloads
15:24:44.488 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.notification
15:24:45.505 [Thread-540] INFO  n.f.g.s.d.p.PebbleIoThread - unhandled message to endpoint -20005 (3 bytes)
15:24:45.606 [Thread-540] INFO  n.f.g.s.d.p.PebbleIoThread - unhandled message to endpoint -20005 (3 bytes)
15:24:46.205 [main] WARN  n.f.g.d.m.MiBandFWInstallHandler - Error reading firmware file: content://downloads/all_downloads/719
java.io.IOException: Error reading firmware file: content://downloads/all_downloads/719
	at nodomain.freeyourgadget.gadgetbridge.devices.miband.MiBandFWHelper.<init>(MiBandFWHelper.java:64) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.devices.miband.MiBandFWInstallHandler.<init>(MiBandFWInstallHandler.java:29) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.devices.miband.MiBandCoordinator.findInstallHandler(MiBandCoordinator.java:62) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.FwAppInstallerActivity.findInstallHandlerFor(FwAppInstallerActivity.java:150) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.FwAppInstallerActivity.onCreate(FwAppInstallerActivity.java:133) ~[na:0.0]
	at android.app.Activity.performCreate(Activity.java:6237) ~[na:0.0]
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) ~[na:0.0]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) ~[na:0.0]
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) ~[na:0.0]
	at android.app.ActivityThread.-wrap11(ActivityThread.java) ~[na:0.0]
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:148) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5417) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) ~[na:0.0]
Caused by: java.io.IOException: Firmware major version should be 1, probably this isn't a MiBand firmware.
	at nodomain.freeyourgadget.gadgetbridge.devices.miband.MiBandFWHelper.<init>(MiBandFWHelper.java:61) ~[na:0.0]
	... 16 common frames omitted
15:24:46.272 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
15:24:46.282 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true

**Comment by ashimokawa** [comment]
@haecker-felix 
Did you open the file from a file manager or just tapped on downloads?
Was your pebble already connected before?

**Comment by haecker-felix** [comment]
Ah. When i select the pbz from a file manager, it's works :).  When i select it direct from the download, it doesnt work.

**Comment by ashimokawa** [comment]
@haecker-felix 
Don't flash a 2.x pbz please ;)

Good to know, I think it is a regression from 0.6.6, where I used the Android API  for zip files instead of the java API, which only operates on files not content provider URLs.

I will have to revert that change in 0.6.8.

**Comment by ashimokawa** [comment]
FYI, in Gadgebridge 0.6.6 it is not possible to install newly compilled 3.x pbw files for the OG pebble. But it should be possible to install old 2.x pbw files.
In 0.6.7 you can install new watch faces compiled with the beta sdk, but as you noted, not from the download manager ;)

**Comment by ashimokawa** [comment]
Actually it never worked for the download manager on FW 3.x , just on FW 2.x, because the file could not be copied to the pbw cache. I will fix this also before 0.6.8.
