### ISSUE TITLE
GardgetBridge tries to install Pebble FW with MiBand installer

### ISSUE THREAD

**Issue by roidelapluie** [Freeyourgadget/Gadgetbridge#202]
When I open a Pebble FW, internally GadgetBridges tries to open it with the MiBand Installer.

I do NOT have a miband.

Log:
```
09:46:51.629 [main] WARN  n.f.g.d.m.MiBandFWInstallHandler - Firmware has a filename that looks like a Pebble app/firmware.
java.io.IOException: Firmware has a filename that looks like a Pebble app/firmware.
        at nodomain.freeyourgadget.gadgetbridge.devices.miband.MiBandFWHelper.<init>(MiBandFWHelper.java:57) ~[na:0.0]
        at nodomain.freeyourgadget.gadgetbridge.devices.miband.MiBandFWInstallHandler.<init>(MiBandFWInstallHandler.java:29) ~[na:0.0]
        at nodomain.freeyourgadget.gadgetbridge.devices.miband.MiBandCoordinator.findInstallHandler(MiBandCoordinator.java:62) ~[na:0.0]
        at nodomain.freeyourgadget.gadgetbridge.activities.FwAppInstallerActivity.findInstallHandlerFor(FwAppInstallerActivity.java:150) ~[na:0.0]
        at nodomain.freeyourgadget.gadgetbridge.activities.FwAppInstallerActivity.onCreate(FwAppInstallerActivity.java:133) ~[na:0.0]
        at android.app.Activity.performCreate(Activity.java:6251) ~[na:0.0]
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) ~[na:0.0]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403) ~[na:0.0]
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520) ~[na:0.0]
        at android.app.ActivityThread.-wrap11(ActivityThread.java) ~[na:0.0]
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) ~[na:0.0]
        at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
        at android.os.Looper.loop(Looper.java:148) ~[na:0.0]
        at android.app.ActivityThread.main(ActivityThread.java:5466) ~[na:0.0]
        at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) ~[na:0.0]
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) ~[na:0.0]
```

**Comment by roidelapluie** [comment]
![screen](https://cloud.githubusercontent.com/assets/291750/12138737/772f1e26-b45b-11e5-8a7d-d414a555f7e4.png)

**Comment by roidelapluie** [comment]
![screen](https://cloud.githubusercontent.com/assets/291750/12138748/8fad4b80-b45b-11e5-85c8-6b45143b7496.png)

**Comment by ashimokawa** [comment]
Have you granted external storage permissions in your shiny new Android 6?

**Comment by roidelapluie** [comment]
nope, now it works, thanks. I was not prompted to add that permission. I installed the app with `./gradlew build installDebug`. Thanks
