### ISSUE TITLE
Uncaught exception while processing Pebble Health updates

### ISSUE THREAD

**Issue by wngr** [Freeyourgadget/Gadgetbridge#236]
Hi,

just this morning Gadgetbridge started to crash. I use Pebble Health as Activitytracker.

Here is the relevant adb log:
````
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol( 9536): DATALOG SENDDATA. id=8, items_left=65535, total length=368
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol( 9536): DATALOG UUID=00000000-0000-0000-0000-000000000000, tag=78(unknown), itemSize=112, itemType=0
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol( 9536): sending ACK (0x85)
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol( 9536): DATALOG SENDDATA. id=21, items_left=65535, total length=594
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol( 9536): DATALOG UUID=00000000-0000-0000-0000-000000000000, tag=81(health - steps), itemSize=99, itemType=0
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.DatalogSessionHealthSteps( 9536): DATALOG (health - steps) *STRIPPED BINARY BLOB*
E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 9536): Uncaught exception: intensity must be > 0java.lang.IllegalArgumentException: intensity must be > 0
E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 9536): 	at nodomain.freeyourgadget.gadgetbridge.impl.GBActivitySample.validate(GBActivitySample.java:27) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 9536): 	at nodomain.freeyourgadget.gadgetbridge.impl.GBActivitySample.<init>(GBActivitySample.java:19) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 9536): 	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.DatalogSessionHealthSteps.store(DatalogSessionHealthSteps.java:81) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 9536): 	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.DatalogSessionHealthSteps.handleMessage(DatalogSessionHealthSteps.java:68) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 9536): 	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol.decodeDatalog(PebbleProtocol.java:1808) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 9536): 	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol.decodeResponse(PebbleProtocol.java:2075) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler( 9536): 	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread.run(PebbleIoThread.java:339) ~[na:0.0]
E/AndroidRuntime( 9536): Process: nodomain.freeyourgadget.gadgetbridge, PID: 9536
E/AndroidRuntime( 9536): 	at nodomain.freeyourgadget.gadgetbridge.impl.GBActivitySample.validate(GBActivitySample.java:27)
E/AndroidRuntime( 9536): 	at nodomain.freeyourgadget.gadgetbridge.impl.GBActivitySample.<init>(GBActivitySample.java:19)
E/AndroidRuntime( 9536): 	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.DatalogSessionHealthSteps.store(DatalogSessionHealthSteps.java:81)
E/AndroidRuntime( 9536): 	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.DatalogSessionHealthSteps.handleMessage(DatalogSessionHealthSteps.java:68)
E/AndroidRuntime( 9536): 	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol.decodeDatalog(PebbleProtocol.java:1808)
E/AndroidRuntime( 9536): 	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol.decodeResponse(PebbleProtocol.java:2075)
E/AndroidRuntime( 9536): 	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread.run(PebbleIoThread.java:339)
I/WindowState(  601): WIN DEATH: Window{3ee488cc u0 nodomain.freeyourgadget.gadgetbridge/nodomain.freeyourgadget.gadgetbridge.activities.ControlCenter}
I/ActivityManager(  601): Process nodomain.freeyourgadget.gadgetbridge (pid 9536) has died
W/ActivityManager(  601): Scheduling restart of crashed service nodomain.freeyourgadget.gadgetbridge/.service.DeviceCommunicationService in 1000ms
````

I stripped the included binary blob, as I dont know what's included in it, but I will send it to a developer upon request.

Please let me know, if you need further info.

**Comment by danielegobbetti** [comment]
@wngr sorry to hear that, it never happened to me to have negative intensity values. The stripped bytes contain the informations outlined here: https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-datalog hence nothing too sensitive.

If you prefer to send it privately to me, I believe you already have my email address, or look at a commit of mine :)

**Comment by wngr** [comment]
Thanks for your answer.

````
05004C2FD35604060F5342024EC20095417F6692009741C66394002961E20D90003C518E198E000C408F048D00E341DEB1C90057414F4BEF008241845BC3007642E659D2004F42CA40BE006241A24EC90054420F53EB006D41062A8D0075411644EA0005000C33D35604060F5442834CC3006F42E457C90064410D41DA006242CC53E2007E426A5FC1007D41104C8E004A42B42B8F000E41171696001F520F1E90000043482292000042DA1EA7000D41701EA40000428A09A7000043C208A6001042391AAC0005009036D35604060F0C420821A20000421F0DA10000428504A50000332A0AA1000042FC0399000042C400A10000323202A00000320000A30000427E059C0000421D03A2000042FA02A30000415E029C0000407300A10000413700A2000042610DA5000500143AD35604060F00421210A6000044850BA30000436814A4000052D80EA5001566E314A3001466C70FA5002F685A14A5000F61C90DC4000050ED029E000F41BF059F000041D7079F0000415601A2000C41B70C9E0000414B09A1000041DF01A3000500983DD35604060F00425D05A10000422408A20000339A13A50010446C1D9E000044031A97001556411DD600114488259E000A42EF169C000C5563119E0025351B1FA5000053F61CA4001033442BA40027568023A4002F31BF1EA50035429318A60005001C41D35604060F1E64C128A4001A53B11FA5000043DE05A60000464109A20000563B0991000025D201940000352201900000521B0CA6001D514314A7000065930FA30000660000A40000562800A40000660000A40000664D00A50000552E029F00
````

**Comment by danielegobbetti** [comment]
Thank you,

I removed the data after saving them locally, just in case :)

**Comment by ashimokawa** [comment]
@wngr 
Could be fixed in git.

**Comment by wngr** [comment]
Works with newest version from F-Droid, thanks.
