### ISSUE TITLE
Firmware update gives error "Element cannot be installed" with Mi Band 1A

### ISSUE THREAD

**Issue by bstreiff** [Freeyourgadget/Gadgetbridge#259]
Using version 0.8.2 (from F-Droid).
Also tried a local build as of b419c93254555e7b84b9519bc87f624921f73030 since I saw there were some firmware-update related changes more recent than 0.8.2.

I'm trying to downgrade from 5.15.11.19 to 5.15.7.14 because I'm hit the no-wakeup-detected issue noted with 5.15.11.19 (according to https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-Information); downgrading firmware was a recommendation noted in #232.

I followed the instructions here: https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-Update
Extracted Mili_1a.fw from MiFit 15.912-1529 (md5sum of Mili_1a.fw is e81eb70e1f3582b27b82bca30f37d189)
Copied it to my device.
Used a file manager to open it.

The Gadgetbridge activity launches, but with the text "Element cannot be installed"; that string only seems to live in Pebble-specific code. I'm not sure what needs to happen to convince the firmware updater that this is really a Mi Band.

I tried turning on debug logs, but the /sdcard/Android/data/nodomain.freeyourgadget.gadgetbridge directory doesn't seem to get created. (This is on a Nexus 5X, which does not have an external SD card.)

**Comment by cpfeiffer** [comment]
Thanks for your thorough explanation! I will try to reproduce the problem later and find a fix for it.

The logfile problem is some kind of Heisenberg: as son as you debug it, it works just fine. 

As a workaround you could manually create the directory. It could also be that Gadgetbridge is not fully restarted because the notification listener is kept alive by the android system.

**Comment by cpfeiffer** [comment]
I cannot reproduce the problem -- I get the screen that allows me to instal the firmware. Same md5sum. I'm still working on it, but if you could somehow enable the logging, e.g. manually creating the directory, that would probably help to spot the problem.

**Comment by ashimokawa** [comment]
Have you granted permission to access the sdcard?

**Comment by cpfeiffer** [comment]
We don't need that. Everybody has implicit permission to create and write his own folder.

**Comment by cpfeiffer** [comment]
This is also the reason why the folder is not just "Gadgetbridge", but the fqdn.

**Comment by cpfeiffer** [comment]
BTW, you could also try to run the JUnit FirmwareTest locally (not on your phone):

``./gradlew --daemon -a --offline  -DMiFirmwareDir=/asset-dir/where/your/firmware/lives  test``

**Comment by ashimokawa** [comment]
I know that.
But you can't install a fw from sdcard if you do not have read access (denied it on Android 6)

We had quite some bugreports about that regarding installation of pebble files.

**Comment by cpfeiffer** [comment]
But wouldn't we get an exception that would clearly indicate the problem?

**Comment by cpfeiffer** [comment]
FYI, I just fixed the creation of the log files directory in #261.

**Comment by bstreiff** [comment]
D'oh. @ashimokawa had the right solution: I didn't have Storage permissions enabled. Evidently this results in Gadgetbridge thinking that the firmware file (which it can't read?) is Pebble firmware.

If I enable Storage permissions, the firmware update works just fine.

So I suppose the real problem here might be "if you don't have permissions configured correctly you get an error that isn't suggestive of that fact".

**Comment by cpfeiffer** [comment]
I had a look at this and it looks like we would just crash in many situations when not having the required permissions. We would have to guard all relevant API calls with permission checks to fix this. And provide infos for users as well.

**Comment by ashimokawa** [comment]
@cpfeiffer 
Where would we crash?
Remember that we only get a "file not found" exception when we dont have the permission. At least on CM13 that is. AOSP might be a different beast but I doubt it.

**Comment by dicer** [comment]
I got the same error message on 7.1.1 when using [AnExplorer Pro](https://f-droid.org/en/packages/dev.dworks.apps.anexplorer.pro/). I worked around it by using [Simple File Manager](https://f-droid.org/packages/com.simplemobiletools.filemanager/). Already updated the Mi Band 3 wiki page to reflect that. No idea what causes this. Maybe the file is passed in a different way?
The file manager that came with my device actually only displayed "The file format is not supported"

**Comment by fvasco** [comment]
I get same error on upgrading my Mi Fit Bip using the file `Mili_chaohu`.
I found this in the log file:

```
17:08:37.670 [main] WARN  n.f.g.d.m.AbstractMiBandFWInstallHandler - Unable to retrieve metadata for: content://media/external/file/11752: Unable to retrieve name for: content://media/external/file/11752
java.io.IOException: Unable to retrieve metadata for: content://media/external/file/11752: Unable to retrieve name for: content://media/external/file/11752
	at nodomain.freeyourgadget.gadgetbridge.util.UriHelper.resolveMetadata(UriHelper.java:152) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.util.UriHelper.get(UriHelper.java:75) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.devices.miband.AbstractMiBandFWHelper.<init>(AbstractMiBandFWHelper.java:47) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.devices.huami.HuamiFWHelper.<init>(HuamiFWHelper.java:36) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.devices.huami.miband3.MiBand3FWHelper.<init>(MiBand3FWHelper.java:30) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.devices.huami.miband3.MiBand3FWInstallHandler.createHelper(MiBand3FWInstallHandler.java:42) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.devices.miband.AbstractMiBandFWInstallHandler.<init>(AbstractMiBandFWInstallHandler.java:44) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.devices.huami.miband3.MiBand3FWInstallHandler.<init>(MiBand3FWInstallHandler.java:32) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.devices.huami.miband3.MiBand3Coordinator.findInstallHandler(MiBand3Coordinator.java:67) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.FwAppInstallerActivity.findInstallHandlerFor(FwAppInstallerActivity.java:196) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.FwAppInstallerActivity.onCreate(FwAppInstallerActivity.java:173) ~[na:0.0]
	at android.app.Activity.performCreate(Activity.java:7136) ~[na:0.0]
	at android.app.Activity.performCreate(Activity.java:7127) ~[na:0.0]
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272) ~[na:0.0]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2896) ~[na:0.0]
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051) ~[na:0.0]
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) ~[na:0.0]
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) ~[na:0.0]
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) ~[na:0.0]
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1811) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:193) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6694) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) ~[na:0.0]
```

I got same error using AnExplorer and Simple File Manager on my Xiaomi Mi A2 Lite with Android 9, no sdcard.

**Comment by IzzySoft** [comment]
@fvasco could that be a broken download? The trace doesn't mention a permission being denied, but unable to obtain metadata, which often happens with broken archives. Did you try again with a fresh download meanwhile?

**Comment by s-hamann** [comment]
My log looks similar. It's not a broken download in my case. The MD5s match the Wiki. I'm at a loss here.
Running Gadgetbridge 0.35.2 on Android 6.0.1.

**Comment by IzzySoft** [comment]
OK, that's strange then. Was worth checking, though.

**Comment by s-hamann** [comment]
I could get it to work by running the following command (via ADB or some other shell on the device):
```
am start -d 'file:///sdcard/path/to/firmware' -a android.intent.action.VIEW
```

Wild guess regarding the cause: `content://` provides an open file handle or something that lets Gadgetbridge access to file's content, but not the file itself. Gadgetbridge does not expect that. I wants a path and accessible metadata, which is what `file://` provides.
Does that make any sense? I know next to nothing about Android internals, so I might by way off here.

**Comment by fvasco** [comment]
I installed app using F-Droid
