### ISSUE TITLE
Cannot connect Android phone to Pebble

### ISSUE THREAD

**Issue by pganssle** [Freeyourgadget/Gadgetbridge#350]
I got a new Pebble Time and tried connecting it to my LG G4 running Android 5.1.1, it is able to pair correctly, but whenever I try to connect the phone over GadgetBridge, it just says "not connected", then when I tap on it, it briefly says "connecting", then immediately falls back to "not connected". No error message is given.

Below is a logcat output for one of the failed connections. Generally I get messages like `n.f.g.e.BluetoothConnectReceiver - won't connect to XX:XX:XX:XX:AA:AA(Pebble Time AABB)` when "reconnect automatically" is not set, and "will connect" when "reconnect automatically" is set, but the result is always the same. I suspect this is the relevant section of the log (there is a typo in the error message, it's not something I typed personally):

```
E/bt-btif (11065): DISCOVERY_COMP_EVT slot id:27, failed to find channle,                                       status:1, scn:0
W/bt-btif (11065): invalid rfc slot id: 27
W/System.err( 5760): java.io.IOException: read failed, socket might closed or timeout, read ret: -1
W/System.err( 5760):    at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:587)
W/System.err( 5760):    at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:598)
W/System.err( 5760):    at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:335)
W/System.err( 5760):    at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread.connect(PebbleIoThread.java:190)
W/System.err( 5760):    at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread.run(PebbleIoThread.java:217)
D/BluetoothAdapterService(327316092)(11065): getState() - mAdapterProperties: com.android.bluetooth.btservice.AdapterProperties@15f03f03

```

I should note that I *was* able to connect my NVidia Shield K1 running CM12.1 to the watch and flash the  latest firmware and some apps, but multiple restarts of both the phone and the watch are not helping to connect the phone.

**Logcat:**
```
D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService( 5760): Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
D/BluetoothAdapterService(327316092)(11065): getState() - mAdapterProperties: com.android.bluetooth.btservice.AdapterProperties@15f03f03
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread( 5760): found service UUID 00000000-0000-XXXX-XXXX-XXXXXXXXXXXX
W/BluetoothAdapter( 5760): getBluetoothService() called with no BluetoothManagerCallback
D/BTIF_SOCK(11065): service_uuid: 00000000-0000-XXXX-XXXX-XXXXXXXXXXXX
I/bt-btif (11065): BTA_JvStartDiscovery
D/IOP_DB_BT(11065): db_query_create: id EnforceMasterRole :: key KEY_BDADDR, value XX:XX:XX:XX:AA:BB
D/IOP_DB_BT(11065): db_query_add_key: key KEY_LMP_MFCT, value 13
D/IOP_DB_BT(11065): db_query_add_key: key KEY_LMP_VER, value 6:7166
D/IOP_DB_BT(11065): db_query_add_key: key KEY_DIR_ALL, value 1
D/IOP_DB_BT(11065): db_query_execute: result 1
D/Ulp_jni ( 1265): Location CB invoked
I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService( 5760): Setting broadcast receivers to: true
I/NotificationServiceEx( 1265): LED remove() : mLights=0|nodomain.freeyourgadget.gadgetbridge|1|null|10230
D/NotificationServiceEx( 1265): updateLightListLocked :r=0|nodomain.freeyourgadget.gadgetbridge|1|null|10230, action=2
D/NotificationServiceEx( 1265): notification=Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 vis=PUBLIC)
I/[SystemUI]PhoneStatusBar( 5424): updateMediaMetaData(false): mMediaMetadata = null
D/IOP_DB_BT(11065): db_query_create: id EnforceMasterRole :: key KEY_BDADDR, value XX:XX:XX:XX:AA:BB
D/IOP_DB_BT(11065): db_query_add_key: key KEY_LMP_MFCT, value 13
D/IOP_DB_BT(11065): db_query_add_key: key KEY_LMP_VER, value 6:7166
D/IOP_DB_BT(11065): db_query_add_key: key KEY_DIR_ALL, value *
D/IOP_DB_BT(11065): db_query_execute: result 1
W/bt-btif (11065): info:x10
D/        (11065): remote version info [XX:XX:XX:XX:AA:BB]: 6, d, 1bfe
I/bt-btif (11065): HAL bt_hal_cbacks->acl_state_changed_cb
D/WifiServerServiceExt( 1265): Connected BT device : 1
I/nodomain.freeyourgadget.gadgetbridge.externalevents.BluetoothConnectReceiver( 5760): got connection attempt
D/[SmartSettings][SmartSettingReceiver](28607): event = android.bluetooth.device.action.ACL_CONNECTED
I/Util    (28607): trigger received  myUserId : 0
I/Util    (28607): trigger received current userID : 0
D/[SmartSettings][SmartSettingReceiver](28607): Bluetooth device connected
I/nodomain.freeyourgadget.gadgetbridge.externalevents.BluetoothConnectReceiver( 5760): won't connect to XX:XX:XX:XX:AA:BB(Pebble Time AABB)
D/[SmartSettings][ITProcessor](28607): sendTrigger
I/LIA_SmartSetting(4.50.7.3)_LogCore(27762): [AppRecommend]LIA Log setMessagePrefix - prefix : [AppRecommend]
I/TrustAgent.Tracker( 8144): [BluetoothConnectionTracker] Bluetooth connect broadast for Pebble Time AABB XX:XX:XX:XX:AA:BB
D/LIA_SmartSetting(4.50.7.3)_AppRecommendBatchService(27762): [AppRecommend]onHandleIntent
D/LIA_SmartSetting(4.50.7.3)_SharedPref(27762): [AppRecommend](getPreference)SETTING STATUS (setting_item_earphone_app) : false
D/LGBluetoothPowerSaveListener(18169): [BTUI] ACL connected => AclLinkCount = 1
D/BluetoothAdapterService(327316092)(11065): getState() - mAdapterProperties: com.android.bluetooth.btservice.AdapterProperties@15f03f03
D/BluetoothAdapterService(327316092)(11065): getState() - mAdapterProperties: com.android.bluetooth.btservice.AdapterProperties@15f03f03
D/BluetoothAdapterService(327316092)(11065): getState() - mAdapterProperties: com.android.bluetooth.btservice.AdapterProperties@15f03f03
D/PowerManagerServiceEx( 1265): updateWakeLockSummaryLocked: checkScreenWakelockList : mWakefulness=Awake, mWakeLockSummary=0x0
D/DisplayManagerServiceEx( 1265): updateExtWakelockEnabled
W/bt-sdp  (11065): process_service_search_attr_rsp
E/bt-btif (11065): DISCOVERY_COMP_EVT slot id:27, failed to find channle,                                       status:1, scn:0
W/bt-btif (11065): invalid rfc slot id: 27
W/System.err( 5760): java.io.IOException: read failed, socket might closed or timeout, read ret: -1
W/System.err( 5760):    at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:587)
W/System.err( 5760):    at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:598)
W/System.err( 5760):    at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:335)
W/System.err( 5760):    at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread.connect(PebbleIoThread.java:190)
W/System.err( 5760):    at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread.run(PebbleIoThread.java:217)
D/BluetoothAdapterService(327316092)(11065): getState() - mAdapterProperties: com.android.bluetooth.btservice.AdapterProperties@15f03f03
D/LIA_SmartSetting(4.50.7.3)_AppRecommendBatchService(27762): [AppRecommend]HeadSet : Bundle[{serviceType=typeConnection, status=1, time=1467311834382, deviceName=Pebble Time AABB, deviceAddress=XX:XX:XX:XX:AA:BB}]
D/LIA_SmartSetting(4.50.7.3)_AppRecommendBatchService(27762): [AppRecommend]Headset plugged
D/LIA_SmartSetting(4.50.7.3)_SharedPref(27762): [AppRecommend](getPreference)SETTING STATUS (setting_item_bluetooth_app) : false
D/LIA_SmartSetting(4.50.7.3)_SharedPref(27762): [AppRecommend](getPreference)CARD STOP? (BT) : true
D/LIA_SmartSetting(4.50.7.3)_AppRecommendBatchService(27762): [AppRecommend]submits a runnable task for connected DB generator.
D/LIA_SmartSetting(4.50.7.3)_SharedPref(27762): [AppRecommend](getPreference)SETTING STATUS (setting_item_bluetooth_app) : false
D/LIA_SmartSetting(4.50.7.3)_SharedPref(27762): [AppRecommend](getPreference)CARD STOP? (BT) : true
I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService( 5760): Setting broadcast receivers to: true
I/NotificationServiceEx( 1265): LED remove() : mLights=0|nodomain.freeyourgadget.gadgetbridge|1|null|10230
D/NotificationServiceEx( 1265): updateLightListLocked :r=0|nodomain.freeyourgadget.gadgetbridge|1|null|10230, action=2
D/NotificationServiceEx( 1265): notification=Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 vis=PUBLIC)
I/[SystemUI]PhoneStatusBar( 5424): updateMediaMetaData(false): mMediaMetadata = null
D/PowerManagerServiceEx( 1265): updateWakeLockSummaryLocked: checkScreenWakelockList : mWakefulness=Awake, mWakeLockSummary=0x0
D/DisplayManagerServiceEx( 1265): updateExtWakelockEnabled
D/PowerManagerServiceEx( 1265): updateWakeLockSummaryLocked: checkScreenWakelockList : mWakefulness=Awake, mWakeLockSummary=0x0
D/DisplayManagerServiceEx( 1265): updateExtWakelockEnabled
D/PowerManagerServiceEx( 1265): updateUserActivitySummaryLocked: mWakefulness=Awake, mUserActivitySummary=0x8, nextTimeout=3365670 (1441829 ms ago)
W/DisplayPowerControllerEx( 1265): updatePowerState() : mPowerRequest.policy = 3, mRequestPolicy = 4, mPowerState.getColorFadeLevel() = 1.0, mPowerState.getScreenState() = 2, mPowerState.getScreenBrightness() = 248, mTriggered = false
W/DisplayPowerControllerEx( 1265): setScreenState : state = 2, isStateChanged = true, returnVal = true
W/DisplayPowerControllerEx( 1265): [aod/alc] mAodStatus = true / policy = 4 / mCoverOpened = true
D/DisplayPowerControllerEx( 1265): [aod/alc] cancelAodAlcForCheckingWakeup()
D/PowerManagerServiceEx( 1265): updateWakeLockSummaryLocked: checkScreenWakelockList : mWakefulness=Awake, mWakeLockSummary=0x0
D/DisplayManagerServiceEx( 1265): updateExtWakelockEnabled
I/bt-btif (11065): HAL bt_hal_cbacks->acl_state_changed_cb
D/WifiServerServiceExt( 1265): Connected BT device : 0
I/BluetoothMapService(11065): onReceive: android.bluetooth.device.action.ACL_DISCONNECTED
V/BluetoothPbapReceiver(11065): PbapReceiver onReceive 
V/BluetoothPbapReceiver(11065): ***********action = android.bluetooth.device.action.ACL_DISCONNECTED
I/TrustAgent.Tracker( 8144): [BluetoothConnectionTracker] Bluetooth disconnect broadast for Pebble Time AABB XX:XX:XX:XX:AA:BB
V/BluetoothPbapReceiver(11065): ***********Calling start service!!!! with action = null
V/BluetoothPbapService(11065): action: android.bluetooth.device.action.ACL_DISCONNECTED
V/BluetoothPbapService(11065): state: -2147483648
```

Here are some potentially related issues:
* [SO: Error happens when connect in android](https://stackoverflow.com/questions/19137580/error-happens-when-connect-in-android)
*  [AOSP Issue 41110: 	Bluetooth failed to get port number](https://code.google.com/p/android/issues/detail?id=41110)
* [Qt: Android Bluetooth Socket Connection fails in some cases.](https://bugreports.qt.io/browse/QTBUG-40172)

All of these seem to be solved in the app, not by the user.

**Comment by pganssle** [comment]
I should note that I also cleared the cache on the `Bluetooth` app, unpaired all other devices and then cleared data on the `Bluetooth` app, to see if it was some issue with that. That doesn't seem to have fixed anything.

**Comment by IzzySoft** [comment]
Just for clarification: The Pebble Time series show up on Android with 2 BT entries. Which one did you pick? GB doesn't (yet) work with the "LE" connection (that was my very first mistake back when I got mine).

**Comment by pganssle** [comment]
@IzzySoft Ah, in an earlier draft of this issue I had mentioned that it was the non-LE one, but I guess that got dropped out when I re-wrote it, sorry. Yes, it was the non-LE.

That said, I MAY have connected to the LE version _first_, the first time I tried connecting this to a phone. I may try doing a factory reset on the Pebble tonight and seeing if maybe it's some sort of issue where the LE connection is stuck in the Pebble's memory or something. Seems dubious.

**Comment by IzzySoft** [comment]
@pganssle Cannot hurt. I had just unpaired the LE and paired the non-LE, then that one connected fine in GB. But maybe I just was more lucky than you've been. Also (not sure if that's connected) I've never had the official Pebble app installed – in case you have, that might still have some LE connection open and get the watch confused (if that's possible, which I don't know).

**Comment by pganssle** [comment]
I installed the Pebble app as a backup but did not use it (never registered), then I deleted it once I was able to flash a firmware with my tablet.

I have now done a factory reset on the watch and nothing has changed. Phone still can't connect, but the tablet can.

**Comment by pganssle** [comment]
I flashed a new ROM on my phone and that fixed the problem, but the ROM was missing some features and I had to go back to the old ROM. I then tried installing the official Pebble bluetooth app to see if the problem was just this particular ROM and the Pebble app did work (it even helpfully deleted all the apps and watchfaces I had on my phone - thanks, Pebble app!). Still not sure how to fix the issue.

**Comment by zuloo** [comment]
Hello, i have the same issue with my Blackberry Priv - updated to the latest Android 6 Rom supplied by Blackberry. so it seems thats not only one edge case but a general problem. Does Gadget Bridge need any root privileges, or some sort of system service, that comes with cm but not the official roms?

**Comment by danielegobbetti** [comment]
Can you please share logs? Further, since you're on android 6, can you go to the settings->app->gadgetbridge->permissions and tell what you see checked there?

**Comment by zuloo** [comment]
hey, I will do that tomorrow, hopefully, i am pretty busy atm

**Comment by zuloo** [comment]
Hello, so finally, here is a log, I just updated to 0.17.2 from fdroid.

somewhere in between, i delete the pebble from the device list, and pair it again, this time, the green heart on the pebble also gets the checked mark, but then it says "There was an error accessing the watchface configuration", and then it keeps on trying to connect indefinetely again.

[gadgetbridge.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/734243/gadgetbridge.txt)

for the permissions, here is the list, I translated those from my german interface...:

Calendar:
read events and confidential data

Contacts:
read contacts

SMS:
receive SMS
send SMS

SD-Card:
read SD-card content

Location:
access coarse location

Phone:
read phone state
call phone
redirect calls

Other:
pairing with Bluethooth
access bluetooth properties

**Comment by danielegobbetti** [comment]
@zuloo please do the following (if you did not solve the issue otherwise, sorry for the delay):
- forget your phone from the pebble watch
- make sure the "always prefer BLE" in the Gadgetbridge/pebble settings is turned off
- quit and make sure Gadgetbridge is not running
- go to the bluetooth settings of your phone
- forget your Pebble (or Pebble LE) device
- turn bluetooth off and on again
- on your Pebble, go to the settings -> bluetooth screen: you should see "now discoverable" on the pebble screen
- on your phone, go to the system bluetooth settings: you should see a Pebble and a Pebble LE device
- pair with the "normal" Pebble device. Do NOT pair the LE device: accept the pairing on both phone and pebble
- launch Gadgetbridge, your Pebble should be listed in the control center
- tap the Pebble

From your logs I noticed you tried to pair your Pebble from within Gadgetbridge. This only works for BLE connection, the standard BT pairing has to be done in the android settings.

**Comment by wobblywob** [comment]
@danielegobbetti 

I have the same problem with: Pebble Time, BlackBerry Priv running Android 6.0.1, 

- removed previous connections from phone and from Pebble
- reboot phone and Pebble
- cleared Gadgetbridge app data.
- paired Pebble (not LE) from Android Settings
- open Gadgetbridge. allow all permissions
- select Pebble from the list
- waiting for reconnect -> connecting -> not connected

Nothing seems to work. @zuloo s.

This might be device specific. I remember I had some problems with notifications on a Vector watch and their support team told me that BB uses something odd for Bluetooth stuff.


[gadgetbridge.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/796663/gadgetbridge.txt)

**Comment by danielegobbetti** [comment]
@wobblywob will take a look at the log later, thanks.

Quick question, did the pebble icon turn blue (when "connecting", even for a very brief period of time) or did it remain grey the whole time?

**Comment by wobblywob** [comment]
@danielegobbetti 

It didn't turn blue, or it was too fast for me to notice. I tried the same watch on a Galaxy S3 with LineageOS on Android N and it worked as expected. I'm fairly certain it's a Priv problem since I have random disconnects with other Bluetooth devices.

**Comment by sandspemd** [comment]
This is a me too report, I'm afraid.

I see the same behaviour as wobbywob.  In my case a Blackberry DTEK60, running Android 6.0.1 and a Pebble Time Steel.  I followed the steps wobblywob listed (including some variations), in addition clearing the Bluetooth Share app data to be sure to start afresh.

For me, on the majority of attempts, the waiting for reconnect -> connecting -> not connected sequence also happens very quickly.  On one or two occasions it has stayed on connecting for a few seconds.  At no time has the icon turned blue.

The pebble app has no problems connecting to the watch on this phone (so maybe they have some sort of workaround).  No problems with the watch and gadgetbridge on a Nexus 5 also running 6.0.1.

The gadgetbridge logfile, however, stays annoyingly empty (the file gets created, but stays at 0 bytes) - not sure what I'm doing wrong there; so I can't verify if I get the same errors or not.

**Comment by IzzySoft** [comment]
Does anyone of you still have these problems? If so: Do you have the "official" Pebble app installed? If so: Do the problems go away once that "official" app is uninstalled? Just bringing this in as walking the issues here today I found someone mentioning exactly that (after uninstalling the "official app", everything worked fine), so there might be some interference.

Should nobody have these problems anymore, I'd suggest we close this issue. After all, it had no activity for about 2.5 years suggesting so :wink:
