### ISSUE TITLE
Excessive log messages after Gadgetbridge quit if continuous HR monitoring was enabled

### ISSUE THREAD

**Issue by walkjivefly** [Freeyourgadget/Gadgetbridge#496]
[log_excerpt.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/691888/log_excerpt.txt)
####Your issue is:
If continuous HR monitoring has been enabled (by entering the Live Activity display) and the user later Quits Gadgetbridge the system log gets filled with messages:
`
W/nodomain.freeyourgadget.gadgetbridge.service.devices.miband2.MiBand2Support: Unable to acquire db for saving realtime samples java.lang.IllegalArgumentException: the bind value at index 2 is null
                                                                                at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:164) ~[na:0.0]
                                                                                at nodomain.freeyourgadget.gadgetbridge.entities.DeviceAttributesDao.bindValues(DeviceAttributesDao.java:76) ~[na:0.0]
                                                                                at nodomain.freeyourgadget.gadgetbridge.entities.DeviceAttributesDao.bindValues(DeviceAttributesDao.java:20) ~[na:0.0]
                                                                                at de.greenrobot.dao.AbstractDao.executeInsert(AbstractDao.java:350) ~[na:0.0]
                                                                                at de.greenrobot.dao.AbstractDao.insert(AbstractDao.java:294) ~[na:0.0]
                                                                                at nodomain.freeyourgadget.gadgetbridge.database.DBHelper.ensureDeviceAttributes(DBHelper.java:462) ~[na:0.0]
                                                                                at nodomain.freeyourgadget.gadgetbridge.database.DBHelper.getDevice(DBHelper.java:387) ~[na:0.0]
                                                                                at nodomain.freeyourgadget.gadgetbridge.service.devices.miband2.MiBand2Support$5.doCurrentSample(MiBand2Support.java:975) ~[na:0.0]
                                                                                at nodomain.freeyourgadget.gadgetbridge.service.devices.miband.RealtimeSamplesSupport.triggerCurrentSample(RealtimeSamplesSupport.java:92) ~[na:0.0]
                                                                                at nodomain.freeyourgadget.gadgetbridge.service.devices.miband.RealtimeSamplesSupport$1.run(RealtimeSamplesSupport.java:43) ~[na:0.0]
                                                                                at java.util.Timer$TimerImpl.run(Timer.java:284) ~[na:0.0]
`

The messages are repeated about once a second. 

####Your wearable device is:
Mi Band 2
HW: v0.1.3.2
FW: v1.0.1.28

####Your android version is:
CM12.1 -20160608-UNOFFICIAL-ido
5.1.1 kernel 3.10.49

**Comment by walkjivefly** [comment]
In trying to fix this it raises an important question: how long should continuous HR monitoring last?

1.  just as long as the user is on the Live Activity display?
2.  until they explicitly cancel the Live Activity display by swiping to the previous (Steps a week) display or using the Back button?
3.  until they Quit Gadgetbridge?
4.  forever?

In the absence of an explicit way to cancel continuous monitoring I lean towards number 3 since they might want to record continuously without having to keep watching the Live Activity display.

**Comment by walkjivefly** [comment]
Working on a fix which implements option 3.

**Comment by cpfeiffer** [comment]
Thanks for the report and investigation! The Live Activity view shall keep monitoring alive only as long as the view is visible. Looks like we somehow fail to properly deactivate it when we leave the activity. See LiveActivityFragment#onMadeInvisibleInActivity() and the same method in MiBand2Support.

Additionally we do need need a different continuous hr monitoring mode outside of the live activity view, but that's a different issue.

**Comment by walkjivefly** [comment]
OK, thanks for the intention guidance for the Live Activity view. I saw there's code to deactivate on invisibility and it even executes on my device but doesn't have the desired effect. Weird stuff happens afterwards! Will keep digging.

**Comment by walkjivefly** [comment]
I thought this no longer reproduces after upgrading GB to 0.17.4 and my MiBand2 FW to 1.0.1.34, at least that was how things looked for a while. I suspected it was a firmware problem so reverted GB to 0.16.0 to check. It looked good for a while but no, it still reproduces, but (so far) only when the device goes out of range and the connection is lost.

Weird stuff continues to happen after the call to onMadeInvisible() regardless. I think this is down to the Android scheduled executor service and/or the fragment handling stuff.

I'm still poking at it.

**Comment by walkjivefly** [comment]
The original reported problem no longer happens with 0.18.4 but the same exception is still raised if the device goes out of range while live monitoring. The previously mentioned weirdness still happens too, and I'm still poking at it. It's definitely related to the scheduled tasks that run during live monitoring and the (Android) fragment handling stuff.

**Comment by walkjivefly** [comment]
The original reported problem no longer happens with 0.18.4 but the same exception is still raised if the device goes out of range while live monitoring. The previously mentioned weirdness still happens too, and I'm still poking at it. It's definitely related to the scheduled tasks that run during live monitoring and the (Android) fragment handling stuff.
