### ISSUE TITLE
Android Studio & java.lang.NullPointerException

### ISSUE THREAD

**Issue by Vebryn** [Freeyourgadget/Gadgetbridge#666]
Hello,

I'm trying to start GB with Android Studio. GB doesn't start. I get following error: 
```
04-25 23:43:45.519 25356-25356/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: nodomain.freeyourgadget.gadgetbridge, PID: 25356
                                                   java.lang.RuntimeException: Unable to create application nodomain.freeyourgadget.gadgetbridge.GBApplication: java.lang.NullPointerException
```

I test with master branch and tag 0.18.5.

Any idea ?

Best regards.

**Comment by cpfeiffer** [comment]
To rule out any configuration problem, you could run 
./gradlew assembleDebug
and then
adb install
the resulting apk.

**Comment by Vebryn** [comment]
I don't think that it's a compiling issue.
`Executing tasks: [:app:assembleDebug]

Configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/nhu/Android/Sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

WARNING: Ignoring Android API artifact com.google.android:android:2.1_r1 for debug
WARNING: Ignoring Android API artifact com.google.android:android:2.1_r1 for debug
:app:buildInfoDebugLoader
:GBDaoGenerator:compileJava UP-TO-DATE
:GBDaoGenerator:processResources NO-SOURCE
:GBDaoGenerator:classes UP-TO-DATE
:GBDaoGenerator:genSources
greenDAO Generator
Copyright 2011-2016 Markus Junginger, greenrobot.de. Licensed under GPL V3.
This program comes with ABSOLUTELY NO WARRANTY
Processing schema version 16...
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/UserAttributesDao.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/UserAttributes.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/UserDao.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/User.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/DeviceAttributesDao.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/DeviceAttributes.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/DeviceDao.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/Device.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/TagDao.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/Tag.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/ActivityDescriptionDao.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/ActivityDescription.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/ActivityDescTagLinkDao.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/ActivityDescTagLink.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/MiBandActivitySampleDao.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/MiBandActivitySample.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/PebbleHealthActivitySampleDao.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/PebbleHealthActivitySample.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/PebbleHealthActivityOverlayDao.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/PebbleHealthActivityOverlay.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/PebbleMisfitSampleDao.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/PebbleMisfitSample.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/PebbleMorpheuzSampleDao.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/PebbleMorpheuzSample.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/HPlusHealthActivityOverlayDao.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/HPlusHealthActivityOverlay.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/HPlusHealthActivitySampleDao.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/HPlusHealthActivitySample.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/CalendarSyncStateDao.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/CalendarSyncState.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/DaoMaster.java
Written /home/nhu/StudioProjects/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/entities/DaoSession.java
Processed 15 entities in 391ms
:app:preBuild
:app:preDebugBuild
:app:checkDebugManifest
:app:prepareComAndroidSupportAnimatedVectorDrawable2531Library
:app:prepareComAndroidSupportAppcompatV72531Library
:app:prepareComAndroidSupportCardviewV72531Library
:app:prepareComAndroidSupportDesign2531Library
:app:prepareComAndroidSupportRecyclerviewV72531Library
:app:prepareComAndroidSupportSupportCompat2531Library
:app:prepareComAndroidSupportSupportCoreUi2531Library
:app:prepareComAndroidSupportSupportCoreUtils2531Library
:app:prepareComAndroidSupportSupportFragment2531Library
:app:prepareComAndroidSupportSupportMediaCompat2531Library
:app:prepareComAndroidSupportSupportV42531Library
:app:prepareComAndroidSupportSupportVectorDrawable2531Library
:app:prepareComAndroidSupportTransition2531Library
:app:prepareDeCkettiLibraryChangelogCkchangelog122Library
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest
:app:processDebugResources
warning: string 'battery_full' has no default translation.
warning: string 'battery_low' has no default translation.
warning: string 'battery_medium' has no default translation.
warning: string 'battery_not_charging' has no default translation.
warning: string 'pref_screen_notification_profile_pebblemsg' has no default translation.
warning: string 'pref_title_notifications_k9mail' has no default translation.
warning: string 'title_activity_appinstaller' has no default translation.


:app:generateDebugSources
:app:incrementalDebugJavaCompilationSafeguard
:app:javaPreCompileDebug
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:app:mergeDebugAssets
:app:processDebugJavaRes NO-SOURCE
:app:transformResourcesWithMergeJavaResForDebug
:app:packageInstantRunResourcesDebug
:app:fastDeployDebugExtractor
:app:generateDebugInstantRunAppInfo
:app:checkManifestChangesDebug
:app:transformClassesWithExtractJarsForDebug
:app:transformClassesWithInstantRunVerifierForDebug
:app:transformClassesWithDependencyCheckerForDebug
:app:compileDebugNdk NO-SOURCE
:app:mergeDebugJniLibFolders
:app:transformNativeLibsWithMergeJniLibsForDebug
:app:transformNativeLibsAndResourcesWithJavaResourcesVerifierForDebug
:app:transformClassesWithInstantRunForDebug
:app:transformClassesEnhancedWithInstantReloadDexForDebug
:app:incrementalDebugTasks
:app:preColdswapDebug
:app:transformClassesWithInstantRunSlicerForDebug
:app:transformClassesWithDexForDebug
:app:validateSigningDebug
:app:transformDexWithInstantRunDependenciesApkForDebug
:app:transformDexWithInstantRunSlicesApkForDebug
:app:packageDebug
:app:buildInfoGeneratorDebug
:app:compileDebugSources
:app:assembleDebug

BUILD SUCCESSFUL

Total time: 41.47 secs`

Logcat
`04-26 22:57:30.024 3084-3084/nodomain.freeyourgadget.gadgetbridge W/ActivityThread: Application nodomain.freeyourgadget.gadgetbridge is waiting for the debugger on port 8100...
04-26 22:57:30.036 3084-3084/nodomain.freeyourgadget.gadgetbridge I/System.out: Sending WAIT chunk
04-26 22:57:30.579 3084-3092/nodomain.freeyourgadget.gadgetbridge I/art: Debugger is active
04-26 22:57:30.658 3084-3084/nodomain.freeyourgadget.gadgetbridge I/System.out: Debugger has connected
04-26 22:57:30.658 3084-3084/nodomain.freeyourgadget.gadgetbridge I/System.out: waiting for debugger to settle...
04-26 22:57:30.860 3084-3084/nodomain.freeyourgadget.gadgetbridge I/System.out: waiting for debugger to settle...
04-26 22:57:31.061 3084-3084/nodomain.freeyourgadget.gadgetbridge I/System.out: waiting for debugger to settle...
04-26 22:57:31.313 3084-3084/nodomain.freeyourgadget.gadgetbridge I/System.out: waiting for debugger to settle...
04-26 22:57:31.525 3084-3084/nodomain.freeyourgadget.gadgetbridge I/System.out: waiting for debugger to settle...
04-26 22:57:31.726 3084-3084/nodomain.freeyourgadget.gadgetbridge I/System.out: waiting for debugger to settle...
04-26 22:57:31.926 3084-3084/nodomain.freeyourgadget.gadgetbridge I/System.out: waiting for debugger to settle...
04-26 22:57:32.126 3084-3084/nodomain.freeyourgadget.gadgetbridge I/System.out: waiting for debugger to settle...
04-26 22:57:32.327 3084-3084/nodomain.freeyourgadget.gadgetbridge I/System.out: waiting for debugger to settle...
04-26 22:57:32.527 3084-3084/nodomain.freeyourgadget.gadgetbridge I/System.out: waiting for debugger to settle...
04-26 22:57:32.727 3084-3084/nodomain.freeyourgadget.gadgetbridge I/System.out: debugger has settled (1498)
04-26 22:57:33.618 3084-3084/nodomain.freeyourgadget.gadgetbridge I/InstantRun: starting instant run server: is main process
04-26 22:57:33.645 3084-3084/nodomain.freeyourgadget.gadgetbridge D/AndroidRuntime: Shutting down VM
                                                                                    
                                                                                    
                                                                                    --------- beginning of crash
04-26 22:57:33.646 3084-3084/nodomain.freeyourgadget.gadgetbridge E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: nodomain.freeyourgadget.gadgetbridge, PID: 3084
                                                                                    java.lang.RuntimeException: Unable to create application nodomain.freeyourgadget.gadgetbridge.GBApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean nodomain.freeyourgadget.gadgetbridge.GBEnvironment.isLocalTest()' on a null object reference
                                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556)
                                                                                        at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                                     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean nodomain.freeyourgadget.gadgetbridge.GBEnvironment.isLocalTest()' on a null object reference
                                                                                        at nodomain.freeyourgadget.gadgetbridge.GBApplication$1.createLogDirectory(GBApplication.java:97)
                                                                                        at nodomain.freeyourgadget.gadgetbridge.Logging.init(Logging.java:67)
                                                                                        at nodomain.freeyourgadget.gadgetbridge.Logging.setupLogging(Logging.java:42)
                                                                                        at nodomain.freeyourgadget.gadgetbridge.GBApplication.setupLogging(GBApplication.java:197)
                                                                                        at nodomain.freeyourgadget.gadgetbridge.GBApplication.onCreate(GBApplication.java:144)
                                                                                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
                                                                                        at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                        at android.os.Looper.loop(Looper.java:135) 
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

**Comment by Vebryn** [comment]
I find out 

GBEnvironment.env().isLocalTest() is causing this exception into Logging method (GBApplication class). Where is GBEnvironment instantiated ?

**Comment by danielegobbetti** [comment]
Reopening this as it seems a real issue. Please don't remove the issue template when opening issues, otherwise they might be closed without much looking into them!
