### ISSUE TITLE
Support for multiple charts

### ISSUE THREAD

**Issue by cpfeiffer** [Freeyourgadget/Gadgetbridge#79]
We will soon have several charts (daily, weekly, monthly, yearly statistics, steps at least). 
We need some groundwork to handle this. 

The first idea is to use a fragment for every "chart screen"  and swipe left and right to switch between charts.

**Comment by danielegobbetti** [comment]
Sometimes a toast is shown with some error. I managed to grab a logcat when it happened:
```
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): Errore eseguendo 'Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int)' on a null object reference'java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int)' on a null object reference
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at nodomain.freeyourgadget.gadgetbridge.activities.charts.WeekStepsChartFragment.setupLegend(WeekStepsChartFragment.java:196) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at nodomain.freeyourgadget.gadgetbridge.activities.charts.WeekStepsChartFragment.refreshWeekBeforeSteps(WeekStepsChartFragment.java:87) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at nodomain.freeyourgadget.gadgetbridge.activities.charts.WeekStepsChartFragment.refreshInBackground(WeekStepsChartFragment.java:53) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractChartFragment$RefreshTask.doInBackground(AbstractChartFragment.java:548) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at nodomain.freeyourgadget.gadgetbridge.database.DBAccess.doInBackground(DBAccess.java:32) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at android.os.AsyncTask$2.call(AsyncTask.java:292) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
I/nodomain.freeyourgadget.gadgetbridge.database.ActivityDatabaseHandler( 8937): Activity query result: 420 samples
I/nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractChartFragment( 8937): Not rendering charts because activity is not available anymore
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): Errore eseguendo 'Attempt to invoke interface method 'nodomain.freeyourgadget.gadgetbridge.impl.GBDevice nodomain.freeyourgadget.gadgetbridge.activities.charts.ChartsHost.getDevice()' on a null object reference'java.lang.NullPointerException: Attempt to invoke interface method 'nodomain.freeyourgadget.gadgetbridge.impl.GBDevice nodomain.freeyourgadget.gadgetbridge.activities.charts.ChartsHost.getDevice()' on a null object reference
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractChartFragment$RefreshTask.doInBackground(AbstractChartFragment.java:548) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at nodomain.freeyourgadget.gadgetbridge.database.DBAccess.doInBackground(DBAccess.java:32) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at android.os.AsyncTask$2.call(AsyncTask.java:292) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
I/nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractChartFragment( 8937): Il tuo sonno: number of samples:420
I/nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractChartFragment( 8937): Not rendering charts because activity is not available anymore
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): Errore eseguendo 'Attempt to invoke interface method 'nodomain.freeyourgadget.gadgetbridge.impl.GBDevice nodomain.freeyourgadget.gadgetbridge.activities.charts.ChartsHost.getDevice()' on a null object reference'java.lang.NullPointerException: Attempt to invoke interface method 'nodomain.freeyourgadget.gadgetbridge.impl.GBDevice nodomain.freeyourgadget.gadgetbridge.activities.charts.ChartsHost.getDevice()' on a null object reference
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractChartFragment$RefreshTask.doInBackground(AbstractChartFragment.java:548) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at nodomain.freeyourgadget.gadgetbridge.database.DBAccess.doInBackground(DBAccess.java:32) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at android.os.AsyncTask$2.call(AsyncTask.java:292) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 8937): 	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
I/nodomain.freeyourgadget.gadgetbridge.activities.charts.AbstractChartFragment( 8937): Not rendering charts because activity is not available anymore
```

**Comment by cpfeiffer** [comment]
I think both exceptions should be fixed with yesterday's merge of the live-activity-data branch (it was fixed there long ago).
