### ISSUE TITLE
Crash when trying to connect to Pebble Time on Android 4.4.4

### ISSUE THREAD

**Issue by Avamander** [Freeyourgadget/Gadgetbridge#943]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
GadgetBridge crashes when trying to connect

#### Your wearable device is:
Pebble Time

#### Your android version is:
Android 4.4.4 (LineageOS 11)

#### Your Gadgetbridge version is:
0.23.2

#### Logs:
```
01-18 12:35:12.119 25453-25453/? V/Zygote: Switching descriptor 33 to /dev/null
01-18 12:35:12.119 25453-25453/? V/Zygote: Switching descriptor 10 to /dev/null
01-18 12:35:12.349 25453-25453/? D/ActivityThread: handleBindApplication:nodomain.freeyourgadget.gadgetbridge
01-18 12:35:12.349 25453-25453/nodomain.freeyourgadget.gadgetbridge D/ActivityThread: setTargetHeapUtilization:0.75
01-18 12:35:12.349 25453-25453/nodomain.freeyourgadget.gadgetbridge D/ActivityThread: setTargetHeapMinFree:2097152
01-18 12:35:12.379 25453-25453/nodomain.freeyourgadget.gadgetbridge I/dalvikvm: Could not find method android.app.NotificationManager.isNotificationPolicyAccessGranted, referenced from method nodomain.freeyourgadget.gadgetbridge.GBApplication.getGrantedInterruptionFilter
01-18 12:35:12.379 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve virtual method 296: Landroid/app/NotificationManager;.isNotificationPolicyAccessGranted ()Z
01-18 12:35:12.379 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x6e at 0x0013
01-18 12:35:12.389 25453-25453/nodomain.freeyourgadget.gadgetbridge I/dalvikvm: Could not find method android.app.NotificationManager.getNotificationPolicy, referenced from method nodomain.freeyourgadget.gadgetbridge.GBApplication.isPriorityNumber
01-18 12:35:12.389 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve virtual method 295: Landroid/app/NotificationManager;.getNotificationPolicy ()Landroid/app/NotificationManager$Policy;
01-18 12:35:12.389 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x6e at 0x0005
01-18 12:35:12.409 25453-25453/nodomain.freeyourgadget.gadgetbridge I/dalvikvm: DexOpt: unable to optimize instance field ref 0x0020 at 0x0b in Lnodomain/freeyourgadget/gadgetbridge/GBApplication;.isPriorityNumber
01-18 12:35:12.419 25453-25453/nodomain.freeyourgadget.gadgetbridge I/dalvikvm: DexOpt: unable to optimize instance field ref 0x0021 at 0x11 in Lnodomain/freeyourgadget/gadgetbridge/GBApplication;.isPriorityNumber
01-18 12:35:12.419 25453-25453/nodomain.freeyourgadget.gadgetbridge I/dalvikvm: DexOpt: unable to optimize instance field ref 0x0020 at 0x1a in Lnodomain/freeyourgadget/gadgetbridge/GBApplication;.isPriorityNumber
01-18 12:35:12.419 25453-25453/nodomain.freeyourgadget.gadgetbridge I/dalvikvm: DexOpt: unable to optimize instance field ref 0x001f at 0x20 in Lnodomain/freeyourgadget/gadgetbridge/GBApplication;.isPriorityNumber
01-18 12:35:13.060 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,033 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [assets/logback.xml] at [assets/logback.xml]
01-18 12:35:13.060 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,071 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.android.LogcatAppender]
01-18 12:35:13.060 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,073 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
01-18 12:35:13.070 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,083 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
01-18 12:35:13.100 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,108 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
01-18 12:35:13.100 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,111 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
01-18 12:35:13.190 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,202 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use zip compression
01-18 12:35:13.190 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,204 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern /storage/sdcard0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/gadgetbridge-%d{yyyy-MM-dd}.%i.log for the active file
01-18 12:35:13.200 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,208 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@42a0a708 - The date pattern is 'yyyy-MM-dd' from file name pattern '/storage/sdcard0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/gadgetbridge-%d{yyyy-MM-dd}.%i.log.zip'.
01-18 12:35:13.200 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,209 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@42a0a708 - Roll-over at midnight.
01-18 12:35:13.200 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,210 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@42a0a708 - Setting initial period to Thu Jan 18 03:10:41 EET 2018
01-18 12:35:13.220 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,230 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
01-18 12:35:13.270 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,276 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: /storage/sdcard0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/gadgetbridge.log
01-18 12:35:13.270 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,276 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [/storage/sdcard0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/gadgetbridge.log]
01-18 12:35:13.270 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,278 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
01-18 12:35:13.270 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,279 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
01-18 12:35:13.270 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,280 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
01-18 12:35:13.270 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,280 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
01-18 12:35:13.270 25453-25453/nodomain.freeyourgadget.gadgetbridge I/System.out: 12:35:13,281 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@42733490 - Registering current configuration as safe fallback point
01-18 12:35:13.270 25453-25453/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.Logging: Gadgetbridge version: 0.23.2
01-18 12:35:13.350 25453-25453/nodomain.freeyourgadget.gadgetbridge E/dalvikvm: Could not find class 'android.bluetooth.le.ScanFilter$Builder', referenced from method nodomain.freeyourgadget.gadgetbridge.devices.huami.HuamiCoordinator.createBLEScanFilters
01-18 12:35:13.350 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve new-instance 83 (Landroid/bluetooth/le/ScanFilter$Builder;) in Lnodomain/freeyourgadget/gadgetbridge/devices/huami/HuamiCoordinator;
01-18 12:35:13.350 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x22 at 0x0007
01-18 12:35:13.360 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: DexOpt: unable to opt direct call 0x01ae at 0x09 in Lnodomain/freeyourgadget/gadgetbridge/devices/huami/HuamiCoordinator;.createBLEScanFilters
01-18 12:35:13.370 25453-25453/nodomain.freeyourgadget.gadgetbridge E/dalvikvm: Could not find class 'android.bluetooth.le.ScanFilter$Builder', referenced from method nodomain.freeyourgadget.gadgetbridge.devices.miband.MiBandCoordinator.createBLEScanFilters
01-18 12:35:13.370 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve new-instance 83 (Landroid/bluetooth/le/ScanFilter$Builder;) in Lnodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandCoordinator;
01-18 12:35:13.370 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x22 at 0x0007
01-18 12:35:13.370 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: DexOpt: unable to opt direct call 0x01ae at 0x09 in Lnodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandCoordinator;.createBLEScanFilters
01-18 12:35:13.380 25453-25453/nodomain.freeyourgadget.gadgetbridge E/dalvikvm: Could not find class 'android.bluetooth.le.ScanFilter$Builder', referenced from method nodomain.freeyourgadget.gadgetbridge.devices.hplus.HPlusCoordinator.createBLEScanFilters
01-18 12:35:13.380 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve new-instance 83 (Landroid/bluetooth/le/ScanFilter$Builder;) in Lnodomain/freeyourgadget/gadgetbridge/devices/hplus/HPlusCoordinator;
01-18 12:35:13.380 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x22 at 0x0007
01-18 12:35:13.380 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: DexOpt: unable to opt direct call 0x01ae at 0x09 in Lnodomain/freeyourgadget/gadgetbridge/devices/hplus/HPlusCoordinator;.createBLEScanFilters
01-18 12:35:13.380 25453-25453/nodomain.freeyourgadget.gadgetbridge E/dalvikvm: Could not find class 'android.bluetooth.le.ScanFilter$Builder', referenced from method nodomain.freeyourgadget.gadgetbridge.devices.no1f1.No1F1Coordinator.createBLEScanFilters
01-18 12:35:13.380 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve new-instance 83 (Landroid/bluetooth/le/ScanFilter$Builder;) in Lnodomain/freeyourgadget/gadgetbridge/devices/no1f1/No1F1Coordinator;
01-18 12:35:13.380 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x22 at 0x0007
01-18 12:35:13.380 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: DexOpt: unable to opt direct call 0x01ae at 0x09 in Lnodomain/freeyourgadget/gadgetbridge/devices/no1f1/No1F1Coordinator;.createBLEScanFilters
01-18 12:35:13.390 25453-25453/nodomain.freeyourgadget.gadgetbridge E/dalvikvm: Could not find class 'android.bluetooth.le.ScanFilter$Builder', referenced from method nodomain.freeyourgadget.gadgetbridge.devices.jyou.TeclastH30Coordinator.createBLEScanFilters
01-18 12:35:13.390 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve new-instance 83 (Landroid/bluetooth/le/ScanFilter$Builder;) in Lnodomain/freeyourgadget/gadgetbridge/devices/jyou/TeclastH30Coordinator;
01-18 12:35:13.390 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x22 at 0x0007
01-18 12:35:13.390 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: DexOpt: unable to opt direct call 0x01ae at 0x09 in Lnodomain/freeyourgadget/gadgetbridge/devices/jyou/TeclastH30Coordinator;.createBLEScanFilters
01-18 12:35:13.560 25453-25453/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.util.GB: Loading apps_blacklist
01-18 12:35:13.560 25453-25453/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.util.GB: Loaded apps_blacklist has 1 entries
01-18 12:35:13.560 25453-25453/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.util.GB: Loading calendars_blacklist
01-18 12:35:13.560 25453-25453/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.util.GB: Loaded calendars_blacklist has 1 entries
01-18 12:35:13.570 25453-25453/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: DeviceCommunicationService is being created
01-18 12:35:13.570 25453-25453/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: no intent
01-18 12:36:13.484 25453-25453/nodomain.freeyourgadget.gadgetbridge I/dalvikvm: Could not find method android.view.Window$Callback.onProvideKeyboardShortcuts, referenced from method android.support.v7.view.WindowCallbackWrapper.onProvideKeyboardShortcuts
01-18 12:36:13.484 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve interface method 22446: Landroid/view/Window$Callback;.onProvideKeyboardShortcuts (Ljava/util/List;Landroid/view/Menu;I)V
01-18 12:36:13.484 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
01-18 12:36:13.494 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
01-18 12:36:13.494 25453-25453/nodomain.freeyourgadget.gadgetbridge I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
01-18 12:36:13.494 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve interface method 22448: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
01-18 12:36:13.494 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
01-18 12:36:13.494 25453-25453/nodomain.freeyourgadget.gadgetbridge I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
01-18 12:36:13.494 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve interface method 22452: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
01-18 12:36:13.494 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
01-18 12:36:13.494 25453-25453/nodomain.freeyourgadget.gadgetbridge I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
01-18 12:36:13.494 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve virtual method 747: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
01-18 12:36:13.494 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
01-18 12:36:13.494 25453-25453/nodomain.freeyourgadget.gadgetbridge I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
01-18 12:36:13.494 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve virtual method 769: Landroid/content/res/TypedArray;.getType (I)I
01-18 12:36:13.494 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
01-18 12:36:13.604 25453-25453/nodomain.freeyourgadget.gadgetbridge I/dalvikvm: Could not find method android.content.Context.getColorStateList, referenced from method android.support.v7.content.res.AppCompatResources.getColorStateList
01-18 12:36:13.604 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve virtual method 490: Landroid/content/Context;.getColorStateList (I)Landroid/content/res/ColorStateList;
01-18 12:36:13.604 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
01-18 12:36:13.634 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/graphics/drawable/Icon;)
01-18 12:36:13.634 25453-25453/nodomain.freeyourgadget.gadgetbridge I/dalvikvm: Could not find method android.widget.ImageView.setImageIcon, referenced from method android.support.v7.widget.AppCompatImageView.setImageIcon
01-18 12:36:13.634 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve virtual method 23053: Landroid/widget/ImageView;.setImageIcon (Landroid/graphics/drawable/Icon;)V
01-18 12:36:13.634 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x6f at 0x0000
01-18 12:36:13.654 25453-25453/nodomain.freeyourgadget.gadgetbridge E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
01-18 12:36:13.654 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve instanceof 211 (Landroid/graphics/drawable/RippleDrawable;) in Landroid/support/v7/widget/AppCompatImageHelper;
01-18 12:36:13.654 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x20 at 0x000c
01-18 12:36:13.894 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/graphics/drawable/Icon;)
01-18 12:36:13.894 25453-25453/nodomain.freeyourgadget.gadgetbridge I/dalvikvm: Could not find method android.widget.ImageButton.setImageIcon, referenced from method android.support.v7.widget.AppCompatImageButton.setImageIcon
01-18 12:36:13.894 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve virtual method 23016: Landroid/widget/ImageButton;.setImageIcon (Landroid/graphics/drawable/Icon;)V
01-18 12:36:13.894 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x6f at 0x0000
01-18 12:36:13.924 25453-25453/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.start
01-18 12:36:13.945 25453-25453/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_deviceinfo
01-18 12:36:13.995 25453-25453/nodomain.freeyourgadget.gadgetbridge I/Adreno-EGL: <qeglDrvAPI_eglInitialize:381>: EGL 1.4 QUALCOMM build:  (CL3869936)
                                                                                  OpenGL ES Shader Compiler Version: 17.01.11.SPL
                                                                                  Build Date: 01/09/14 Thu
                                                                                  Local Branch: kk_2.7_rb1
                                                                                  Remote Branch: 
                                                                                  Local Patches: 
                                                                                  Reconstruct Branch: 
01-18 12:36:14.035 25453-25453/nodomain.freeyourgadget.gadgetbridge D/OpenGLRenderer: Enabling debug mode 0
01-18 12:36:14.205 25453-25453/nodomain.freeyourgadget.gadgetbridge I/dalvikvm: Could not find method android.support.v7.widget.LinearLayoutCompat.drawableHotspotChanged, referenced from method android.support.design.internal.ForegroundLinearLayout.drawableHotspotChanged
01-18 12:36:14.205 25453-25453/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: VFY: unable to resolve virtual method 18827: Landroid/support/v7/widget/LinearLayoutCompat;.drawableHotspotChanged (FF)V
01-18 12:36:14.205 25453-25453/nodomain.freeyourgadget.gadgetbridge D/dalvikvm: VFY: replacing opcode 0x6f at 0x0000
01-18 12:36:14.405 25453-25453/nodomain.freeyourgadget.gadgetbridge I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@428224c8 time:72400505
01-18 12:36:16.497 25453-25453/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
01-18 12:36:16.717 25453-25453/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol: setting always ACK PebbleKit to false
01-18 12:36:16.717 25453-25453/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol: setting enable PebbleKit support to true
01-18 12:36:16.727 25453-25791/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread: found service UUID 00001101-0000-1000-8000-00805f9b34fb
01-18 12:36:16.727 25453-25791/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread: found service UUID 00000000-0000-1000-8000-00805f9b34fb
01-18 12:36:16.727 25453-25791/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread: found service UUID 00000000-deca-fade-deca-deafdecacaff
01-18 12:36:16.727 25453-25791/nodomain.freeyourgadget.gadgetbridge W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
01-18 12:36:16.737 25453-25791/nodomain.freeyourgadget.gadgetbridge D/BluetoothSocket: connect(), SocketState: INIT, mPfd: {ParcelFileDescriptor: FileDescriptor[57]}
01-18 12:36:16.758 25453-25453/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
01-18 12:36:17.328 25453-25453/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.externalevents.BluetoothConnectReceiver: connection attempt detected from or to B0:B4:48:9B:85:27(Pebble Time 8527)
01-18 12:36:17.518 25453-25791/nodomain.freeyourgadget.gadgetbridge W/dalvikvm: threadid=13: thread exiting with uncaught exception (group=0x41e8fce0)
01-18 12:36:17.538 25453-25791/nodomain.freeyourgadget.gadgetbridge E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler: Uncaught exception: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
                                                                                                                                    	at android.app.ContextImpl.startActivity(ContextImpl.java:1098) ~[na:0.0]
                                                                                                                                    	at android.app.ContextImpl.startActivity(ContextImpl.java:1085) ~[na:0.0]
                                                                                                                                    	at android.content.ContextWrapper.startActivity(ContextWrapper.java:311) ~[na:0.0]
                                                                                                                                    	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread.connect(PebbleIoThread.java:170) ~[na:0.0]
                                                                                                                                    	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread.run(PebbleIoThread.java:197) ~[na:0.0]
01-18 12:36:17.548 25453-25791/nodomain.freeyourgadget.gadgetbridge E/AndroidRuntime: FATAL EXCEPTION: Thread-3168
                                                                                      Process: nodomain.freeyourgadget.gadgetbridge, PID: 25453
                                                                                      android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
                                                                                          at android.app.ContextImpl.startActivity(ContextImpl.java:1098)
                                                                                          at android.app.ContextImpl.startActivity(ContextImpl.java:1085)
                                                                                          at android.content.ContextWrapper.startActivity(ContextWrapper.java:311)
                                                                                          at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread.connect(PebbleIoThread.java:170)
                                                                                          at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread.run(PebbleIoThread.java:197)

```

**Comment by ashimokawa** [comment]
Turn off background js then

**Comment by Avamander** [comment]
I'd like to use it?

**Comment by IzzySoft** [comment]
Then decide: Use BGJS and have it crashing – or resist using it until that issue is fixed and have the remains working. I'm sitting in the same boat, so have my sympathies :wink:

**Comment by cpfeiffer** [comment]
Then bug fdroid to build our last release (where the crash is supposed to be fixed).

**Comment by IzzySoft** [comment]
@cpfeiffer they do their best. Undermanned, and the build server just repaired if I understand correctly.

May I remind you of my offer from a year ago (I hope you know what I'm referring to)? If the key question was solved meanwhile, that could provide a relief. Dropping in the term "reproducible build" in this context, there wouldn't even be a conflict then.

**Comment by cpfeiffer** [comment]
@IzzySoft Thanks for the reminder. We still have no easy way to switch between differently signed versions without manual export, renaming, uninstall, renaming back, install and import. I've opened #945 for this.

And sorry, I really didn't mean to push them even if it sounded like that. I am grateful for their service and I for one am patient :-)

**Comment by cpfeiffer** [comment]
Closing in favor of #863

**Comment by IzzySoft** [comment]
@cpfeiffer as I mentioned, reproducible builds would be one way. But I'm afraid that's either too late now (as too many folks already use the F-Droid signed app), too early (as the "migration approach" is not yet implemented) – or simply the wrong time: wasn't there something about a new package name a while ago? If that path is followed, definitely keep "reproducible builds" in mind to start on the right leg :wink:
