### ISSUE TITLE
Gadgetbridge crashes as soon as I open the statistics page

### ISSUE THREAD

**Issue by kaefert** [Freeyourgadget/Gadgetbridge#973]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

As soon as I open the statistics page of my Mi Fit 2 device, Gadgetbridge crashes and leaves this error in the log:

```
07:28:03.859 [main] ERROR n.f.g.LoggingExceptionHandler - Uncaught exception: Attempt to invoke virtual method 'android.graphics.drawable.Drawable com.github.mikephil.charting.data.BaseEntry.getIcon()' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable com.github.mikephil.charting.data.BaseEntry.getIcon()' on a null object reference
	at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:574) ~[na:0.0]
	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:264) ~[na:0.0]
	at android.view.View.draw(View.java:17120) ~[na:0.0]
	at android.view.View.updateDisplayListIfDirty(View.java:16102) ~[na:0.0]
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3792) ~[na:0.0]
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3772) ~[na:0.0]
	at android.view.View.updateDisplayListIfDirty(View.java:16065) ~[na:0.0]
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3792) ~[na:0.0]
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3772) ~[na:0.0]
	at android.view.View.updateDisplayListIfDirty(View.java:16065) ~[na:0.0]
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3792) ~[na:0.0]
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3772) ~[na:0.0]
	at android.view.View.updateDisplayListIfDirty(View.java:16065) ~[na:0.0]
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3792) ~[na:0.0]
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3772) ~[na:0.0]
	at android.view.View.updateDisplayListIfDirty(View.java:16065) ~[na:0.0]
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3792) ~[na:0.0]
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3772) ~[na:0.0]
	at android.view.View.updateDisplayListIfDirty(View.java:16065) ~[na:0.0]
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3792) ~[na:0.0]
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3772) ~[na:0.0]
	at android.view.View.updateDisplayListIfDirty(View.java:16065) ~[na:0.0]
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3792) ~[na:0.0]
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3772) ~[na:0.0]
	at android.view.View.updateDisplayListIfDirty(View.java:16065) ~[na:0.0]
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3792) ~[na:0.0]
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3772) ~[na:0.0]
	at android.view.View.updateDisplayListIfDirty(View.java:16065) ~[na:0.0]
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3792) ~[na:0.0]
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3772) ~[na:0.0]
	at android.view.View.updateDisplayListIfDirty(View.java:16065) ~[na:0.0]
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656) ~[na:0.0]
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662) ~[na:0.0]
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770) ~[na:0.0]
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2883) ~[na:0.0]
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2691) ~[na:0.0]
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2298) ~[na:0.0]
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1306) ~[na:0.0]
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6579) ~[na:0.0]
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871) ~[na:0.0]
	at android.view.Choreographer.doCallbacks(Choreographer.java:683) ~[na:0.0]
	at android.view.Choreographer.doFrame(Choreographer.java:619) ~[na:0.0]
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857) ~[na:0.0]
	at android.os.Handler.handleCallback(Handler.java:751) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:154) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6316) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) ~[na:0.0]
```

#### Your wearable device is:
Mi Band 2
HW: V.0.1.3.3
FW: 1.0.1.53

#### Your android version is:
7.0

#### Your Gadgetbridge version is:
0.24.2
The issue started happening with a previous version - I thought maybe updating will fix the problem, therefore I updated to the latest version that FDroid had (which looks like it's 0.24.2 to me) - But that sadly didn't help.

**Comment by cpfeiffer** [comment]
Thanks for the report and I'm sorry for this. This is unfortunately not quite under our control, since it happens in the charting library we use.

We have a workaround in place in #960 and just need to make a new release.

**Comment by kaefert** [comment]
Thanks for the explanation.

When you say you have a workaround in place you mean a workaround in code that needs a new build to be applied? So in other words: There is no way for me to get Gadgetbridge working again other than waiting for a new release or look into building myself (which would be a hassle because of different apk signing keys so lot's of manual migration work back an forth)?

Or does maybe clearing some cache help? I mean I did not experience this issue before and it seems like lot's of users don't experience it now, so what causes this issue for me?

**Comment by kaefert** [comment]
Hah! I closed all apps, cleared the cache (in android app manager) opened gadgetbridge again and I can look at my statistics page again!

**Comment by cpfeiffer** [comment]
Great that you found a way to fix it for you! I have no idea why clearing the cache helps and I don't know how to reproduce this issue at all.

**Comment by TaaviE** [comment]
@cpfeiffer Any clue what the charting library could be caching?
